### ISSUE TITLE
TouchableOpacity and TouchableWithoutFeedback components not working when using in VoiceOver mode in iOS

### ISSUE THREAD

**Issue by Sriman97** [ammarahm-ed/react-native-actions-sheet#107]
Double tap actions on TouchableOpacity and TouchableWithoutFeedback aren't working when using VoiceOver in iOS. Also, i see that when the ActionSheet is launched. The focus goes to the background first and then to action sheet upon swipe gesture. Is there a way the focus could first be made to come onto the action sheet?

**Comment by Sriman97** [comment]
@ammarahm-ed Any update on this issue. incase the issue is not clear, I could provide some more information. Basically its about gestures not working on TouchableOpacity and TouchableWithoutFeedback on iOS. Was wondering if the issue is similar to this: https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#pressables--touchables-are-not-working-on-android 
(Though this talks about Android)

**Comment by ammarahm-ed** [comment]
Could you elaborate more? Maybe a video or an example app would help me understand your problem.

**Comment by Sriman97** [comment]
Actually i was able to figure out the issue. For some reason, when the action sheet top level component doesnt have flex:1 and gestureEnabled is set to true, the gesture actions (accessibility ones) werent working for the touchable components.  (i.e Double tapping the screen to perform 'press' action on the Touchable button wasnt working.

So to unblock myself, i have set the flex property to 1 and removed the gestureEnabled attribute. (i.e. false)
