### ISSUE TITLE
Spacing at top after upgrading to 0.5.1

### ISSUE THREAD

**Issue by raquelmsmith** [ammarahm-ed/react-native-actions-sheet#108]
_Thank you for this amazing package!! I've gotten so much great use out of it._ 

I just updated to 0.5.1 so that I could use the `keyboardMode="position"` prop. That's working great!

But now all of my action sheets have this odd styling/behavior:

When opening an action sheet for the first time, there is extra space at the top of the sheet (above the gesture handler grey bar thing):

![Simulator Screen Shot - iPhone 12 - 2021-08-18 at 14 17 56](https://user-images.githubusercontent.com/18598166/129973781-b780ae2f-115e-4014-89e3-23a915b0d9b4.png)

The content is actually in the correct place as it relates to the bottom of the sheet.

However, if I close the sheet, then open it again, the content is pushed up to the top of the sheet, and there's a bunch of extra space at the bottom. 

![Simulator Screen Shot - iPhone 12 - 2021-08-18 at 14 18 01](https://user-images.githubusercontent.com/18598166/129974035-fdda113d-03a9-4c2e-83c4-d215fcbba231.png)

Here's a gif of the open/close to show the difference:

![2021-08-18 14-17-18 2021-08-18 14_17_48](https://user-images.githubusercontent.com/18598166/129974092-1a757754-9e25-4a67-b27e-bfc31f6a0abc.gif)

Because the extra space is above the gesture bar and because was working fine til I upgraded to 0.5.1 I have to assume it's an issue with the library.

Thanks!!

**Comment by ammarahm-ed** [comment]
> _Thank you for this amazing package!! I've gotten so much great use out of it._ 
> 
> I just updated to 0.5.1 so that I could use the `keyboardMode="position"` prop. That's working great!
> 
> But now all of my action sheets have this odd styling/behavior:
> 
> When opening an action sheet for the first time, there is extra space at the top of the sheet (above the gesture handler grey bar thing):
> 
> ![Simulator Screen Shot - iPhone 12 - 2021-08-18 at 14 17 56](https://user-images.githubusercontent.com/18598166/129973781-b780ae2f-115e-4014-89e3-23a915b0d9b4.png)
> 
> The content is actually in the correct place as it relates to the bottom of the sheet.
> 
> However, if I close the sheet, then open it again, the content is pushed up to the top of the sheet, and there's a bunch of extra space at the bottom. 
> 
> ![Simulator Screen Shot - iPhone 12 - 2021-08-18 at 14 18 01](https://user-images.githubusercontent.com/18598166/129974035-fdda113d-03a9-4c2e-83c4-d215fcbba231.png)
> 
> Here's a gif of the open/close to show the difference:
> 
> ![2021-08-18 14-17-18 2021-08-18 14_17_48](https://user-images.githubusercontent.com/18598166/129974092-1a757754-9e25-4a67-b27e-bfc31f6a0abc.gif)
> 
> Because the extra space is above the gesture bar and because was working fine til I upgraded to 0.5.1 I have to assume it's an issue with the library.
> 
> Thanks!! 

I know that is an issue. For now you can set `drawUnderStatusBar prop to false and it will work as expected.

**Comment by raquelmsmith** [comment]
That does help, but leaves a bunch of extra space at the bottom. Will that extra space remain, so I'm fine to change my implementation, or do you anticipate that the extra space issue will be resolved?

**Comment by raquelmsmith** [comment]
That works, thanks!
