### ISSUE TITLE
Keyboard.removeListener was deprecated in React-Native 0.65

### ISSUE THREAD

**Issue by simonas-kralikas** [ammarahm-ed/react-native-actions-sheet#109]
`Keyboard.removeListener()` was deprecated in React-Native 0.65 in favor of `remove()` applied to the listener return event.

This causes a crash. Could we get a patch?

**Comment by simonas-kralikas** [comment]
Proposed changes at  #110

**Comment by punndcoder28** [comment]
Just encountered the same issue. Is there any workaround we can try in the mean time?

**Comment by ammarahm-ed** [comment]
> Just encountered the same issue. Is there any workaround we can try in the mean time?

I will publish a new version with the fix soon

**Comment by ammarahm-ed** [comment]
Fixed in v0.5.2
