### ISSUE TITLE
Animated node with tag 61 does not exists

### ISSUE THREAD

**Issue by flavioribeirojr** [ammarahm-ed/react-native-actions-sheet#113]
I have an issue redering the action sheet that contains a input. Whenever I focus the input I get this error.

I have the same component being rendered on another screen that don't have the bottom tab bar displayed.

I am using **react-native** and **react-navigation**.

![Screenshot_1629748459](https://user-images.githubusercontent.com/21633230/130511149-5e8f9e40-8efa-4e82-aa45-eeb25860130e.png)

Here is a video demonstrating the issue:

https://user-images.githubusercontent.com/21633230/130511498-2710e559-d18a-4080-98a1-08ffcdb99ec5.mp4

**Comment by ammarahm-ed** [comment]
What version of actionsheet are you using

**Comment by flavioribeirojr** [comment]
react-native-actions-sheet@0.4.9

Should I upgrade to latest?

**Comment by ammarahm-ed** [comment]
> react-native-actions-sheet@0.4.9
> 
> Should I upgrade to latest?

Yes

**Comment by flavioribeirojr** [comment]
I upgraded but still got the same error

**Comment by flavioribeirojr** [comment]
Sorry - I just found out that this has nothing to do with react-native-actions-sheet library. Actually it is another component(**react-native-popup-menu**) that was throwing this error.

**Comment by Nziranziza** [comment]
I just happen to experience the same issue, I upgrade to react native version 0.70.2 
I have version 0.8.8 of react-native-actions-sheet
The app crashes when I focus on a textInput that's inside action sheet

**Comment by vi0dine** [comment]
Same as @Nziranziza :/
