### ISSUE TITLE
Keyboard.removeListener() deprecated in React native 0.65

### ISSUE THREAD

**Issue by chazzaoui** [ammarahm-ed/react-native-actions-sheet#114]
First of all big thanks for creating and maintaining this package!

Question is it possible to change the removeListener() for the remove() method on the event subscription returned by addListener(). Since it will be deprecated and causes a crash on ios and android.

![Screenshot 2021-08-23 at 23 43 48](https://user-images.githubusercontent.com/22476835/130523454-360b493a-04f7-48fb-8648-db9c69c7a06e.png)

Using version: 0.5.1

**Comment by ammarahm-ed** [comment]
> First of all big thanks for creating and maintaining this package!
> 
> Question is it possible to change the removeListener() for the remove() method on the event subscription returned by addListener(). Since it will be deprecated and causes a crash on ios and android.
> 
> ![Screenshot 2021-08-23 at 23 43 48](https://user-images.githubusercontent.com/22476835/130523454-360b493a-04f7-48fb-8648-db9c69c7a06e.png)
> 
> Using version: 0.5.1

It's fixed on master

**Comment by chazzaoui** [comment]
It seems that the latest merge only reverts the previous fix. It still uses the remove listener function

**Comment by ammarahm-ed** [comment]
> It seems that the latest merge only reverts the previous fix. It still uses the remove listener function

Send a PR fixing the bug.

**Comment by chazzaoui** [comment]
https://github.com/ammarahm-ed/react-native-actions-sheet/pull/115 

Should resolve this issue

**Comment by efstathiosntonas** [comment]
@ammarahm-ed for some reason, currently master (`0.5.3`) does not have the fix from this [PR](https://github.com/ammarahm-ed/react-native-actions-sheet/pull/115)

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed for some reason, current master (`0.5.3`) does not have the fix from this [PR](https://github.com/ammarahm-ed/react-native-actions-sheet/pull/115)

I will fix it in a bit

**Comment by efstathiosntonas** [comment]
@ammarahm-ed we need backwards compatibility with rn < 0.65, I can provide a fix if you want

**Comment by efstathiosntonas** [comment]
@ammarahm-ed  something like: 

```


```
const ReactNativeVersion = require('react-native/Libraries/Core/ReactNativeVersion');

const v = parseInt(
      ReactNativeVersion.version.major + ReactNativeVersion.version.minor,
      10
    );

```

and then use it as: 

```
if (v >= 65) {
      const showSubscription = Keyboard.addListener(showEvent, () =>
        onKeyboardShow()
      );
      const hideSubscription = Keyboard.addListener(hideEvent, () =>
        onKeyboardHide()
      );

      return () => {
        showSubscription.remove();
        hideSubscription.remove();
      };
    } else {
      Keyboard.addListener(showEvent, onKeyboardShow);
      Keyboard.addListener(hideEvent, onKeyboardHide);

      return () => {
        Keyboard.removeListener(showEvent, onKeyboardShow);
        Keyboard.removeListener(hideEvent, onKeyboardHide);
      };
    }

```

for more info you could check this PR i've made for @rnhooks/keyboard: https://github.com/react-native-hooks/keyboard/blob/65619ebbb2314a7a90c35a9b26607c11ab54f0ec/src/Keyboard.tsx
