### ISSUE TITLE
Double swipe for actionsheet closing not working

### ISSUE THREAD

**Issue by EmreKorpe** [ammarahm-ed/react-native-actions-sheet#117]
hi thanks for this legendary library, in the example, the scrollview is waiting for the scroll to be full screen after the scroll is completed on the up scroll, this is very nice. Can we make the same process wait for it to scroll again so that it closes when the scroll down is complete?

**Comment by ammarahm-ed** [comment]
I think that is how it works right now. But depending on how fast you swipe it might take parent scroll and scroll it down instead of the child. However primarily it waits for the child scroll to reach top and then it will scroll the parent.

**Comment by EmreKorpe** [comment]
yes, as you said, if the scrolling is fast, it closes completely without waiting. It would be great if it waits for the second scroll at the default height without considering the scroll speed. If it works as you say, I may have set it up wrong in my project. i will check again

**Comment by ammarahm-ed** [comment]
Scrolling behaviour has completely changed in v0.8.0. Now user must lift the finger once to close the sheet once the scrollview reaches top or swipe from  outside the ScrollView to close the Sheet.
