### ISSUE TITLE
running tsc command reveals a lot of TS errors

### ISSUE THREAD

**Issue by RazaShehryar** [ammarahm-ed/react-native-actions-sheet#118]
Hi,

Upon running `tsc` command in the terminal, I came across a lot of different errors related to TS. If you want, I can create a PR for it.

Below is the log for all the errors

```
node_modules/react-native-actions-sheet/src/index.tsx:119:5 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

119     this.currentOffsetFromBottom = this.props.initialOffsetFromBottom;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:202:15 - error TS2532: Object is possibly 'undefined'.

202     waitAsync(closeAnimationDuration / 1.5).then(() => {
                  ~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:204:13 - error TS2532: Object is possibly 'undefined'.

204         if (bottomOffset > 0) {
                ~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:205:29 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

205           this.snapToOffset(bottomOffset);
                                ~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:208:38 - error TS2532: Object is possibly 'undefined'.

208             this.actionSheetHeight * initialOffsetFromBottom +
                                         ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:210:13 - error TS2532: Object is possibly 'undefined'.

210             extraScroll,
                ~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:213:11 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

213           this.currentOffsetFromBottom = initialOffsetFromBottom;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:219:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

219         this.currentOffsetFromBottom = initialOffsetFromBottom;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:252:10 - error TS7006: Parameter 'x' implicitly has an 'any' type.

252         (x, y, width, height) => {
             ~

node_modules/react-native-actions-sheet/src/index.tsx:252:13 - error TS7006: Parameter 'y' implicitly has an 'any' type.

252         (x, y, width, height) => {
                ~

node_modules/react-native-actions-sheet/src/index.tsx:252:16 - error TS7006: Parameter 'width' implicitly has an 'any' type.

252         (x, y, width, height) => {
                   ~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:252:23 - error TS7006: Parameter 'height' implicitly has an 'any' type.

252         (x, y, width, height) => {
                          ~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:277:25 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

277         await waitAsync(delayActionSheetDrawTime);
                            ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:280:27 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

280           await waitAsync(delayActionSheetDrawTime);
                              ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:287:25 - error TS2532: Object is possibly 'undefined'.

287         await waitAsync(delayActionSheetDrawTime / 2);
                            ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:290:27 - error TS2532: Object is possibly 'undefined'.

290           await waitAsync(delayActionSheetDrawTime / 2);
                              ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:348:46 - error TS2532: Object is possibly 'undefined'.

348       if (verticalOffset - this.prevScroll > springOffset * 0.75 || this.initialScrolling) {
                                                 ~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:351:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

351         this.currentOffsetFromBottom =
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:352:42 - error TS2532: Object is possibly 'undefined'.

352           this.currentOffsetFromBottom < this.props.initialOffsetFromBottom
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:358:11 - error TS2532: Object is possibly 'undefined'.

358           extraScroll;
              ~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:373:46 - error TS2532: Object is possibly 'undefined'.

373       if (this.prevScroll - verticalOffset > springOffset) {
                                                 ~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:406:7 - error TS2532: Object is possibly 'undefined'.

406       this.props.extraScroll;
          ~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:535:27 - error TS2532: Object is possibly 'undefined'.

535     if (this.prevScroll - this.props.springOffset > this.offsetY) {
                              ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:540:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

540         this.currentOffsetFromBottom = this.props.initialOffsetFromBottom;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:569:28 - error TS7006: Parameter '_event' implicitly has an 'any' type.

569   _onDeviceLayout = async (_event) => {
                               ~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:584:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

584         safeMarginFromTop = measuredPadding;
            ~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:585:44 - error TS2532: Object is possibly 'undefined'.

585         this.indicatorTranslateY.setValue(-measuredPadding);
                                               ~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:603:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

603         paddingTop: measuredPadding,
            ~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:612:34 - error TS2532: Object is possibly 'undefined'.

612       ? this.actionSheetHeight * this.props.initialOffsetFromBottom +
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:614:7 - error TS2532: Object is possibly 'undefined'.

614       this.props.extraScroll
          ~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:615:47 - error TS2532: Object is possibly 'undefined'.

615       : this.actionSheetHeight + correction + this.props.extraScroll;
                                                  ~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:616:5 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

616     this.currentOffsetFromBottom = this.props.initialOffsetFromBottom;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-actions-sheet/src/index.tsx:622:20 - error TS7006: Parameter 'item' implicitly has an 'any' type.

622   _keyExtractor = (item) => item;
                       ~~~~

node_modules/react-native-actions-sheet/src/index.tsx:751:41 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

751                         ...getElevation(elevation)
```

**Comment by ammarahm-ed** [comment]
> Hi,
> 
> Upon running `tsc` command in the terminal, I came across a lot of different errors related to TS. If you want, I can create a PR for it.
> 
> Below is the log for all the errors
> 
> node_modules/react-native-actions-sheet/src/index.tsx:119:5 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 119     this.currentOffsetFromBottom = this.props.initialOffsetFromBottom;
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:202:15 - error TS2532: Object is possibly 'undefined'.
> 
> 202     waitAsync(closeAnimationDuration / 1.5).then(() => {
>                   ~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:204:13 - error TS2532: Object is possibly 'undefined'.
> 
> 204         if (bottomOffset > 0) {
>                 ~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:205:29 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 205           this.snapToOffset(bottomOffset);
>                                 ~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:208:38 - error TS2532: Object is possibly 'undefined'.
> 
> 208             this.actionSheetHeight * initialOffsetFromBottom +
>                                          ~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:210:13 - error TS2532: Object is possibly 'undefined'.
> 
> 210             extraScroll,
>                 ~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:213:11 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 213           this.currentOffsetFromBottom = initialOffsetFromBottom;
>               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:219:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 219         this.currentOffsetFromBottom = initialOffsetFromBottom;
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:252:10 - error TS7006: Parameter 'x' implicitly has an 'any' type.
> 
> 252         (x, y, width, height) => {
>              ~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:252:13 - error TS7006: Parameter 'y' implicitly has an 'any' type.
> 
> 252         (x, y, width, height) => {
>                 ~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:252:16 - error TS7006: Parameter 'width' implicitly has an 'any' type.
> 
> 252         (x, y, width, height) => {
>                    ~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:252:23 - error TS7006: Parameter 'height' implicitly has an 'any' type.
> 
> 252         (x, y, width, height) => {
>                           ~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:277:25 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 277         await waitAsync(delayActionSheetDrawTime);
>                             ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:280:27 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 280           await waitAsync(delayActionSheetDrawTime);
>                               ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:287:25 - error TS2532: Object is possibly 'undefined'.
> 
> 287         await waitAsync(delayActionSheetDrawTime / 2);
>                             ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:290:27 - error TS2532: Object is possibly 'undefined'.
> 
> 290           await waitAsync(delayActionSheetDrawTime / 2);
>                               ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:348:46 - error TS2532: Object is possibly 'undefined'.
> 
> 348       if (verticalOffset - this.prevScroll > springOffset * 0.75 || this.initialScrolling) {
>                                                  ~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:351:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 351         this.currentOffsetFromBottom =
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:352:42 - error TS2532: Object is possibly 'undefined'.
> 
> 352           this.currentOffsetFromBottom < this.props.initialOffsetFromBottom
>                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:358:11 - error TS2532: Object is possibly 'undefined'.
> 
> 358           extraScroll;
>               ~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:373:46 - error TS2532: Object is possibly 'undefined'.
> 
> 373       if (this.prevScroll - verticalOffset > springOffset) {
>                                                  ~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:406:7 - error TS2532: Object is possibly 'undefined'.
> 
> 406       this.props.extraScroll;
>           ~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:535:27 - error TS2532: Object is possibly 'undefined'.
> 
> 535     if (this.prevScroll - this.props.springOffset > this.offsetY) {
>                               ~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:540:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 540         this.currentOffsetFromBottom = this.props.initialOffsetFromBottom;
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:569:28 - error TS7006: Parameter '_event' implicitly has an 'any' type.
> 
> 569   _onDeviceLayout = async (_event) => {
>                                ~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:584:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 584         safeMarginFromTop = measuredPadding;
>             ~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:585:44 - error TS2532: Object is possibly 'undefined'.
> 
> 585         this.indicatorTranslateY.setValue(-measuredPadding);
>                                                ~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:603:9 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 603         paddingTop: measuredPadding,
>             ~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:612:34 - error TS2532: Object is possibly 'undefined'.
> 
> 612       ? this.actionSheetHeight * this.props.initialOffsetFromBottom +
>                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:614:7 - error TS2532: Object is possibly 'undefined'.
> 
> 614       this.props.extraScroll
>           ~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:615:47 - error TS2532: Object is possibly 'undefined'.
> 
> 615       : this.actionSheetHeight + correction + this.props.extraScroll;
>                                                   ~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:616:5 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 616     this.currentOffsetFromBottom = this.props.initialOffsetFromBottom;
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:622:20 - error TS7006: Parameter 'item' implicitly has an 'any' type.
> 
> 622   _keyExtractor = (item) => item;
>                        ~~~~
> 
> node_modules/react-native-actions-sheet/src/index.tsx:751:41 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
>   Type 'undefined' is not assignable to type 'number'.
> 
> 751                         ...getElevation(elevation),

If you can fix these errors, send a PR. Also i am not getting any errors but maybe my ts config is not correct.

**Comment by RazaShehryar** [comment]
I created a separate branch for the fixes but it is giving me this

<img width="499" alt="Screenshot 2021-08-30 at 4 51 32 PM" src="https://user-images.githubusercontent.com/42263739/131334890-208361e7-9b90-42d4-8ea4-93d6049e3d97.png">

**Comment by RobertMetcalfePhorest** [comment]
Any Luck? same issue here

**Comment by ammarahm-ed** [comment]
> I created a separate branch for the fixes but it is giving me this
> 
> <img width="499" alt="Screenshot 2021-08-30 at 4 51 32 PM" src="https://user-images.githubusercontent.com/42263739/131334890-208361e7-9b90-42d4-8ea4-93d6049e3d97.png">
> 

You have to fork this repo then make the fixes and send a PR.

**Comment by RazaShehryar** [comment]
> > I created a separate branch for the fixes but it is giving me this
> > <img alt="Screenshot 2021-08-30 at 4 51 32 PM" width="499" src="https://user-images.githubusercontent.com/42263739/131334890-208361e7-9b90-42d4-8ea4-93d6049e3d97.png">
> 
> You have to fork this repo then make the fixes and send a PR.

done, here's the link:

https://github.com/ammarahm-ed/react-native-actions-sheet/pull/119

**Comment by ammarahm-ed** [comment]
Fix is merged on master.
