### ISSUE TITLE
Getting "_reactNative.Keyboard.removeListener is not a function" Error 

### ISSUE THREAD

**Issue by Mogul123** [ammarahm-ed/react-native-actions-sheet#121]
I get the following error: _reactNative.Keyboard.removeListener is not a function"

when navigating back. I assume this might have to do something with using React-Native 0.65?

Everthing works fine, except when I navigate to the previous screen. 

`This error is located at:
    in ActionSheet (at postBottomSheet.js:27)
    in RCTView (at View.js:32)
    in View (at postBottomSheet.js:26)
    in ActionSheetModul (at postScreen.js:282)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in SafeAreaView (at baseScreen.js:28)
    in BaseScreen (at postScreen.js:281)
    in PostScreen (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:209)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:32)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:243)
    in AnimatedComponent (at createAnimatedComponent.js:296)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:243)
    in AnimatedComponent (at createAnimatedComponent.js:296)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in RCTView (at View.js:32)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RCTView (at View.js:32)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:616)
    in RCTView (at View.js:32)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:32)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at homeFeedStack.js:24)
    in HomeFeedStack (at SceneView.tsx:126)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:118)
    in SceneView (at useDescriptors.tsx:209)
    in RCTView (at View.js:32)
    in View (at BottomTabView.tsx:55)
    in SceneContent (at BottomTabView.tsx:172)
    in RCTView (at View.js:32)
    in View (at ResourceSavingScene.tsx:68)
    in RCTView (at View.js:32)
    in View (at ResourceSavingScene.tsx:63)
    in ResourceSavingScene (at BottomTabView.tsx:166)
    in RCTView (at View.js:32)
    in View (at src/index.native.js:123)
    in ScreenContainer (at BottomTabView.tsx:146)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at BottomTabView.tsx:145)
    in BottomTabView (at createBottomTabNavigator.tsx:45)
    in BottomTabNavigator (at coreAppStack.js:49)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:429)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at coreAppStack.js:48)
    in CoreAppStack (at App.js:98)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:429)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at App.js:97)
    in Routes (at App.js:119)
    in AuthRoute (at App.js:118)
    in App (at renderApplication.js:48)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:133)
    in AppContainer (at renderApplication.js:41)`

Thank you very much!

**Comment by ammarahm-ed** [comment]
Fixed. 0.5.4
