### ISSUE TITLE
If I open action sheet once and close it I could not open it again frequently ,I basically could not perform any action for next 3 to 4 seconds once I close The Action Sheet

### ISSUE THREAD

**Issue by usamadesigner** [ammarahm-ed/react-native-actions-sheet#134]

**Comment by MyloCarson** [comment]
Using  `setTimeout` solves this issue

const handlePress = () => {
    networkInfoSheetRef.current.hide();
    setTimeout(() => {
      networkSelectSheetRef.current.show();
    }, 500);
  };
