### ISSUE TITLE
Snap to close distance

### ISSUE THREAD

**Issue by Jalson1982** [ammarahm-ed/react-native-actions-sheet#135]
Hello @ammarahm-ed. Want to ask you do you have a plan to add more customization. For example, if you have an action sheet and you open the keyboard and you try to swipe down the sheet it is not possible if you do not swipe to the end. So I was thinking maybe I can help on this if you do not have time or similar that we can define closing distance. For example, it would be good if we can set when the keyboard is open closing distance is keyboard height. I would really love to hear your opinion.

**Comment by ammarahm-ed** [comment]
Did you try using the `springOffset` prop?
