### ISSUE TITLE
FlatList don't scroll as child of ActionSheet

### ISSUE THREAD

**Issue by MyloCarson** [ammarahm-ed/react-native-actions-sheet#136]
https://user-images.githubusercontent.com/12560014/142203604-4300fa78-72f8-4961-83b7-2d730e68aeb1.mp4

**Comment by ammarahm-ed** [comment]
Did you try the example app? You are doing something incorrectly.

**Comment by MyloCarson** [comment]
Could you kindly point me to the example? Per the documentation, a ScrollView was used to illustrate the nestedScrollingEnabled feature

**Comment by ammarahm-ed** [comment]
Go to main project/example/App.js. You can also clone the repo and try running example app. 

Also try importing `FlatList` from `react-native-gesture-handler` instead and use that.

**Comment by MyloCarson** [comment]
Awesome. I'd try that out right away

**Comment by MyloCarson** [comment]
thanks a lot @ammarahm-ed it works.
