### ISSUE TITLE
issue action sheet doesn't open after closing another modal that has/hasn't keyboard opened

### ISSUE THREAD

**Issue by joseortiz9** [ammarahm-ed/react-native-actions-sheet#137]
### issue
The actionsheet doesnt open when `ref.current?.setModalVisible(true)` is called inside a setTimeout. Also doesnt opens when is tried to open after closing another modal that had the keyboard opened.

The expected behavior are the first 15 seconds where we open a modal, select something and open the action sheet after that. You can see the 18 second where we select something from the modal with the keyboard opened but nothing appears, only the overlay of the actionsheet, here is the issue. 
In my opinion, needs a delay to open the actionsheet but when I try to put the `ref.current?.setModalVisible(true)` inside a setTimeout callback the ref always returns null, I dont know why this happens. But when is outside always works...

In the last seconds of the video we can see that one time the action sheet opened even with the keyboard opened, so it pretty weird, in android sometimes it doesnt open completed and just the header or middle of content.

### code
```jsx
const handleSelectProduct = useCallback((newProduct) => {
    setSelectedProduct(newProduct);
    setShowSelectModal(false);//close modal
    console.log("out",actionSheetRef.current); //the ref has the right object
    //if is outside the callback it works sometimes
    if (newProduct) actionSheetRef.current?.setModalVisible(true);
    setTimeout(() => {
        console.log("in",actionSheetRef.current); //always null
        //if is inside never works
        //if (newProduct) actionSheetRef.current?.setModalVisible(true);
    }, Platform.OS === "ios" ? 300 : 0);
}, [setSelectedProduct, setShowSelectModal, actionSheetRef]);
```

### Versions
"native-base": "^2.15.2",
"react": "17.0.1",
"react-dom": "17.0.1",
"react-native": "0.64.3",
"react-native-actions-sheet": "^0.5.6",

### video

https://user-images.githubusercontent.com/26872450/142474001-04594105-5a43-4729-b867-60333a2c32c7.MP4

help me out @ammarahm-ed  please!

I havent seen any issue like this.

**Comment by anatooly** [comment]
I have some issue for iOS and use
```
if (Platform.OS === 'ios') {
      Keyboard.dismiss()

      setTimeout(() => {
        // my action, with pause 500 ms, when 0-300 — not show nothing without background
      }, 500)
    } else {
      // android
    }
```

**Comment by joseortiz9** [comment]
> I have some issue for iOS and use
> 
> ```
> if (Platform.OS === 'ios') {
>       Keyboard.dismiss()
> 
>       setTimeout(() => {
>         // my action, with pause 500 ms, when 0-300 — not show nothing without background
>       }, 500)
>     } else {
>       // android
>     }
> ```

Hey thanks for the recommendation, the problems is that when I put the `ref.current?.setModalVisible(true)` inside the `setTimeout` it never works :( the ref is always null, doesn't it happens to you?

**Comment by hblab-huongdv** [comment]
@joseortiz9 Do you have a solution for fixing it? I have same issue

**Comment by ammarahm-ed** [comment]
Try this:

```js

const sleep = async (ms) => new Promise(resolve => setTimeout(() => resolve(),ms));

const handleSelectProduct = useCallback(async (newProduct) => {
    setSelectedProduct(newProduct); // Set the product
    setShowSelectModal(false); // Hide the modal
    await sleep(300); // Wait 300ms
    if (newProduct) actionSheetRef.current?.setModalVisible(true); // Display the modal

}, [setSelectedProduct, setShowSelectModal, actionSheetRef]);
```
