### ISSUE TITLE
Property 'removeListener' does not exist on type 'KeyboardStatic'.

### ISSUE THREAD

**Issue by andreirat** [ammarahm-ed/react-native-actions-sheet#141]
When if I run ` tsc --noEmit --skipLibCheck && eslint . --ext .js,.jsx,.ts,.tsx` , it will throw an error like in the image attached.

I have `react-native: 0.66.4` 

![Screenshot 2022-01-03 at 17 08 57](https://user-images.githubusercontent.com/17424445/147946844-13062cbb-fe01-4cfb-adcd-f06761137125.png)

**Comment by ammarahm-ed** [comment]
Fixed this.
