### ISSUE TITLE
Nested scrolling not working

### ISSUE THREAD

**Issue by andrea-martinez** [ammarahm-ed/react-native-actions-sheet#142]
I have a FlatList with fixed height inside the Actionsheet and nested scrolling seems not to work even after adding the necessary code from the documentation:

`nestedScrollEnabled={true}`
`onScrollEndDrag={() => actionSheetRef.current?.handleChildScrollEnd()}`
`onScrollAnimationEnd={() => actionSheetRef.current?.handleChildScrollEnd()}`
`onMomentumScrollEnd={() => actionSheetRef.current?.handleChildScrollEnd()}`

The same FL in page scrolls as expected. I tried also eliminating any configuration from the ActionSheet but it didn't help.
Checked on Android.

**Comment by ammarahm-ed** [comment]
@andrea-martinez try to import FlatList from `react-native-gesture-handler` and use it instead.

**Comment by andrea-martinez** [comment]
@ammarahm-ed thanks a lot, it works. I think this should be mentioned in the documentation.

**Comment by umer-viabletree** [comment]
> @andrea-martinez try to import FlatList from `react-native-gesture-handler` and use it instead.

working on ios fine but not in android .

**Comment by ammarahm-ed** [comment]
@umer-viabletree  You have to set `nestedScrollingEnabled` prop on android to get it to work on FlatList.

**Comment by jake-carpenter** [comment]
> @umer-viabletree You have to set `nestedScrollingEnabled` prop on android to get it to work on FlatList.

Nasty little detail I didn't know about. That fixed it not working on Android for me.

**Comment by JaifDev** [comment]
Facing this issue, Using with Flatlist from gesture handler is working but the sheet disappears after a moment
