### ISSUE TITLE
Release without jcenter

### ISSUE THREAD

**Issue by swatiredhu17** [ammarahm-ed/react-native-actions-sheet#145]
### Dependancy removal request

```bash
Just creating an issue so we can track when a version without jcenter can be pulled for our app releases.
```

**Platform:** Android

**Comment by ammarahm-ed** [comment]
@swatiredhu17 The library does not contain any platform specific code. So you should not be having any problems.

**Comment by swatiredhu17** [comment]
@ammarahm-ed Oops! I added issue to wrong package.

Closing now.
Appreciate your quick response!!
