### ISSUE TITLE
`keyboardShouldPersistTaps` not working as expected

### ISSUE THREAD

**Issue by derick-bai** [ammarahm-ed/react-native-actions-sheet#150]
In my case, I have text input and buttons on the action sheet. And I'd like to be able to tap the button while keeping the keyboard visible.

Below is how I use the action sheet (simplified by removing styles and irrelevant props/content)
```
<ActionSheet
  headerAlwaysVisible={true}
  keyboardShouldPersistTaps='always'
>
  <TextInput onChangeText={() => {}} />
  <Pressable onPress={() => {}}>
    <Text>Button</Text>
  </Pressable>
</ActionSheet>
```

**Expected result**
After entering something in the input text, being able to press the button without dismissing the keyboard.

**Actual result**
The first tap dismissed the keyboard, and the action sheet goes back to the bottom of the screen. Need a second tap to trigger the press event on the button.

I also tried setting `handled` to `keyboardShouldPersistTaps` and the result is the same.

Version: **0.5.8**

**Comment by ammarahm-ed** [comment]
Use `keyboardDismissMode` prop

**Comment by derick-bai** [comment]
Found the issue. The action sheet in my case is wrapped as a reusable component. And in the place it is used, its direct parent is a scroll view. By setting `keyboardShouldPersistTaps` to "always" on the parent scroll view I got the desired behavior.

Thanks for the response anyway.

**Comment by justinjoyn** [comment]
For me there is no ScrollView wrapping the content or the action sheet. I'm still facing this issue.
@ammarahm-ed  What do you mean by "Use keyboardDismissMode prop"? I tried all possible combinations without any luck.

**Comment by Nicoalz** [comment]
Same problem, any solution ?
