### ISSUE TITLE
`onEndReached` not called consistently for nested `FlatList`

### ISSUE THREAD

**Issue by AChesarone** [ammarahm-ed/react-native-actions-sheet#153]
When using a `FlatList` in the `ActionSheet`, the `onEndReached` function is not consistently called when reaching the end of the `FlatList` content. Is there any specific configuration that needs to be done in order for this to work?

Note that this worked previously, but stoped working after updating RN to 0.66.4. Current `react-native-actions-sheet` version is 0.6.0. Also importing `FlatList` from `react-native-gesture-handler`.

**Comment by zzeerak** [comment]
+1. facing the same issue. 
My onEndReached is never called. What could be the issue?

**Comment by retr0-spection** [comment]
Setting this prop within ActionSheet `containerStyle={position:'absolute', bottom:0}`  worked for me.

**Comment by ammarahm-ed** [comment]
Fixed in v0.8.0. New version coming soon.
