### ISSUE TITLE
Actionsheet is dismissed  automatically when app is in background for a while

### ISSUE THREAD

**Issue by imjaad9090** [ammarahm-ed/react-native-actions-sheet#16]
Hi, I have noticed this behaviour recently that when the action sheet is opened and if i open some other app for some time and return to my application, the action sheet is in dismissed state and not even completely dismissed but i guess it looks like in blurred state. 

**Scenario** : I am using actionsheet to allow user to enter the OTP sent via messages, so if he opens messaging application and returns back, the actionsheet is gone.
Can we do anything about this..
Thanks

**Comment by ammarahm-ed** [comment]
I will try to reproduce it and see if it could be fixed. The ActionSheet basically uses a modal to show itself. So if showing a dialog is doing the same when in background, we would need to look deeper however maybe its some bug on my end, but let me look. Thank you for reporting.

**Comment by ammarahm-ed** [comment]
So I have been multi-tasking for sometime now with the ActionSheet opened in the example app. It does not close or blur out. I have kept it in background for 15 to 20 minutes. Try to check if you face the same problem in the example.

**Comment by imjaad9090** [comment]
Great so i will have to look at it, maybe i am not using the package properly. Can you share the code you tested with i.e the default settings/props.
thanks

**Comment by ammarahm-ed** [comment]
I tested it in the example provided in the library.

You can clone this project and run the example to test.

**Comment by imjaad9090** [comment]
Ok i will, thanks

**Comment by ammarahm-ed** [comment]
This issue is stale, I am closing it now, if you face a problem, reopen it.
