### ISSUE TITLE
Scrolling doesn't work when using FlatList or ScrollView

### ISSUE THREAD

**Issue by elitedev0403** [ammarahm-ed/react-native-actions-sheet#163]
I need to show list using FlatList or ScrollView inside Action sheet but it doesn't work now.
Here's my code below:
<View style={{flex: 1}}>
  <ActionSheet 
       containerStyle={{ margin: -10, }}
       indicatorStyle={{ margin: 0, }} 
       id={'chat_sheet'} 
       ref={chatRef} 
       delayActionSheetDrawTime={0} 
       statusBarTranslucent 
       bounceOnOpen={true} 
       drawUnderStatusBar={true} 
       bounciness={4} 
       gestureEnabled={true} 
       defaultOverlayOpacity={0.3}> 
           <View style={{ height: deviceHeight * 0.78, backgroundColor: 'white', borderTopLeftRadius: 30, borderTopRightRadius: 30, paddingBottom: 10 }}> 
                 <ScrollView style={{ flex: 1, backgroundColor: '#333', padding: 10, paddingBottom: 30}}> 
                     {CHAT_HISTORY.map((item, index) => ( 
                           <TouchableOpacity style={{borderWidth: 1, margin: 10, padding: 20}}>
		                 {item.user.name}
                           </TouchableOpacity>
                     ))}
                 </ScrollView>
           </View>
      </ActionSheet>
</View>

**Comment by bokovski** [comment]
same problem
