### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ActionSheet> & Pick<Readonly<Props>

### ISSUE THREAD

**Issue by kumar-aakash86** [ammarahm-ed/react-native-actions-sheet#164]
I am trying to use this library to add actionsheet in my project. 
But when I am trying to add it its children its showing error & not accepting children.
<img width="793" alt="Screenshot 2022-04-19 at 12 11 15 PM" src="https://user-images.githubusercontent.com/8749247/163946963-583112b5-6eec-4734-95c4-87e569d21133.png">

I tried checking the index.d.ts file & it don't contain any definition for children in it.

Can you check if this is removed or is there any other prop to add children?

**Comment by francesco-clementi-92** [comment]
Same issue

**Comment by ammarahm-ed** [comment]
Fixed. Thanks @francesco-clementi-92
