### ISSUE TITLE
White Bar at bottom after keyboard dismissal and sheet disappears when TextInput + autofocus is used

### ISSUE THREAD

**Issue by dhuber666** [ammarahm-ed/react-native-actions-sheet#17]
Hiho,

first of all: Awesome library!

**EDIT: Look at my second post the first problem has been solved**

Second:

I have a minor problem and it might be my fault but I really don't know how I can solve it. I'm really stuck. 

So when I open the action sheet and then type into the TextArea of course the keyboard comes up and the whole sheet gets way slower (this works perfectly). But when I close or dismiss the keyboard I have a white margin on the bottom of the still open sheet:

![rn3](https://user-images.githubusercontent.com/15130832/78883136-5b42bd80-7a59-11ea-9361-a336fa1c95ff.PNG)

So this is where I'm left at. I'm almost done with finishing up this chapter but this problem has to be solved before I can continue. 

This is the whole code I'm using the lib.

The file I'm using it is a custom BottomTabBar from `react-navigation`, here is the code: 

https://pastebin.com/rtRS0ZM1

Would be really cool if you could help me out here :) 

**Spec:**

Windows
Android Emu
RN 0.62

**Comment by dhuber666** [comment]
I solved it by also give it a custom `containerStyle`.
But I have a new problem:

When I have a `TextInput` inside the custom component that pops up and give it the prop `autofocus`, when I open the modal the keyboard snaps up and then the modal completely disappears, but the keyboard stays open (ios only). 

When I close the keyboard and open the modal again, everything works as expected. So the first opening of the modal gives me this strange behavior. 

What can I do about it? The code for the component that does all this is in my post above (pastebin). 

Ty so much again for this awesome library?

**Comment by ammarahm-ed** [comment]
Hi,

Thank you for opening the issue, I will look into it and report back ASAP.

**Comment by ammarahm-ed** [comment]
Also I am pushing a point release to fix a few issues you listed here. Thank you very much for using this library!

**Comment by ammarahm-ed** [comment]
I am closing this issue for now, if you face any problem, you can open it again or create a new one.

**Comment by Ritik5Prasad** [comment]
just use isModal false
