### ISSUE TITLE
Displaying sheets inside modal with same id

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-actions-sheet#176]
Hey!

I'm using a `SheetProvider` to render some bottom sheets inside a modal, if I keep the same sheet id as the one registered on the top-level `SheetProvider`, it works, but once you close the modal, the screen freeze, and I'm pretty sure that its because it tries to open a sheet on the background as well because it shares the same name than the one registered on the top provider.  
However, if I use another sheet id, it works well. I'd expect calls to `SheetManager.show` to not bubble to top providers but just to its closest one, this way we don't need to change the id of the sheet each time we use a nested provider.

**Comment by Nziranziza** [comment]
Having similar issue

**Comment by ammarahm-ed** [comment]
v0.8.0 makes it possible to use the same id for the sheet in multiple contexts. However when opening the Sheet with Sheet Manager you still need to provide the context in which you need to present the Sheet.
