### ISSUE TITLE
Returning values from a sheet that was opened

### ISSUE THREAD

**Issue by gremlin529** [ammarahm-ed/react-native-actions-sheet#177]
Relatively new to RN so I'm sorry if this is something that should be obvious to one skilled in the arts, because it's definitely not to me. How would I go about returning something to the code which called the show on the Actions Sheet, Let's say I was using it to replace a drop down in a desktop app, and allow the person to select an item. I've been trying to declare the sheet as an inline function to the component using useCallback but I'm having a lot of compile issues which makes me feel like this is perhaps not the way this should be done.

**Comment by ammarahm-ed** [comment]
Fixed in v0.8.0
