### ISSUE TITLE
[BUGGGG]white screen after wrap app by SheetProvider

### ISSUE THREAD

**Issue by fukemy** [ammarahm-ed/react-native-actions-sheet#181]
plz help, after wrap my app inside SheetProvider i got white screen
![Screen Shot 2022-07-19 at 16 36 18](https://user-images.githubusercontent.com/8202437/179718992-78e13faa-edf6-429d-99d2-7e69a9ee1b59.png)

![Screen Shot 2022-07-19 at 16 36 29](https://user-images.githubusercontent.com/8202437/179719039-50291890-e3cd-409b-b777-b774cdae4fe7.png)
![Screen Shot 2022-07-19 at 16 36 46](https://user-images.githubusercontent.com/8202437/179719128-2112306f-2f9f-4b81-b1f0-abe2da29d5b1.png)

![Screen Shot 2022-07-19 at 16 37 13](https://user-images.githubusercontent.com/8202437/179719239-38524d18-a488-40dd-8bef-58eabfc658d6.png)

version:  0.7.1

**Comment by fukemy** [comment]
@ammarahm-ed

**Comment by fukemy** [comment]
tested with Example, still white. screen 
![Screen Shot 2022-07-20 at 11 47 18](https://user-images.githubusercontent.com/8202437/179899156-465a1ab3-ef7b-49e7-a1bf-2580cd157fbd.png)

**Comment by fukemy** [comment]
plz help

**Comment by fukemy** [comment]
![Screen Shot 2022-07-20 at 12 08 19](https://user-images.githubusercontent.com/8202437/179901453-7fe4a5da-290f-438b-a0d1-a6ee58efd0c6.png)

**Comment by fukemy** [comment]
![Screen Shot 2022-07-20 at 12 08 55](https://user-images.githubusercontent.com/8202437/179901528-1a36a552-26a7-45ca-adee-ba785b4a3617.png)

**Comment by fukemy** [comment]
DEAD lib

**Comment by ammarahm-ed** [comment]
@fukemy have to tried to install the master branch directly. It should work normally

**Comment by ammarahm-ed** [comment]
Fixed in v0.8.0
