### ISSUE TITLE
Overlay is not taking full screen

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-actions-sheet#184]
Hey! I just updated to version `0.8.0` and I love it! Well done man, you did a really good job there. However, after upgrading, for some reason, the overlay is not taking all the screen height (see attached screenshot). I'm using a global sheet provider which is rendered at the top of the component tree. I also tested using a local `SheetProvider` and still doesn't work. 

<details>
<summary>Screenshot</summary>

![Simulator Screen Shot - iPhone 13 - 2022-08-21 at 22 52 44](https://user-images.githubusercontent.com/3316818/185829753-db1e91cc-96a4-437b-9b00-83f9191def51.png)
</details>

**Comment by ammarahm-ed** [comment]
I will fix this asap.

**Comment by focux** [comment]
Awesome man! Some heads up, just tested on Android and it's happening as well, seems related to the status bar/safe area because on Android the only part that it doesn't cover is the status bar and iOS as well.

**Comment by ammarahm-ed** [comment]
@focus just fixed it. it was a slight miscalculation.

**Comment by ammarahm-ed** [comment]
Try v0.8.1. i tested on ios, android & web. Looks good.

**Comment by focux** [comment]
Just tested it and it's working. Thank you so much!
