### ISSUE TITLE
Using together with SafeAreaView?

### ISSUE THREAD

**Issue by tibbe** [ammarahm-ed/react-native-actions-sheet#185]
In noticed by default that the UI overlaps parts of the system UI on the bottom of the screen (the horizontal "divider" on iOS) I tried to include a `SafeAreaView` from react-native-safe-area-context like below but it had no effect. What's the right way to avoid the sheet being overlapped by any "indentations" at the bottom of the screen?

```tsx
<ActionSheet id={props.sheetId}>
  <SafeAreaView>
    ...
  </SafeAreaView>
</ActionSheet>
```

**Comment by ammarahm-ed** [comment]
@tibbe 

```
const insets = useSafeAreaInsets(); // from react-native-safe-area-context

```
Then add some bottom padding in `containerStyle` prop

**Comment by tibbe** [comment]
Worked great. Thanks. Feel free to close this bug.

P.S. I guess this will be a common first problem for new users to solve so perhaps worth documenting.

**Comment by ammarahm-ed** [comment]
@tibbe I agree. I will add this to docs or maybe support it somehow Internally 😌
