### ISSUE TITLE
Bottom safe area is not applied as the layout grows

### ISSUE THREAD

**Issue by Kaung-Htet-Hein** [ammarahm-ed/react-native-actions-sheet#188]
@ammarahm-ed 

Please check the behavior in below video. Safe area is working properly when the sheet first opened.  As the view is added in ScrollView, bottom safe area is not applied. Am I missing something? Can someone help me fix this issue?

I am using v0.8.1
react-native v0.67.4

https://user-images.githubusercontent.com/100679042/186083958-11f0d00e-97bb-4935-83ed-531701492e32.mov

This is my code below

```
<ActionSheet
			id={id}
			bounceOnOpen={true}
			bounciness={4}
			gestureEnabled={true}
			defaultOverlayOpacity={0.3}
			containerStyle={[actionSheetStyle, containerStyle]}
			CustomHeaderComponent={CustomHeaderComponent}
			onClose={onClose}
			onBeforeShow={onBeforeShow}
			keyboardShouldPersistTaps={keyboardShouldPersistTaps}
		>
			<ScrollView
				nestedScrollEnabled
				contentContainerStyle={[
					Gutters.regularHPadding,
					Gutters.largeBMargin,
					layoutCenter && Layout.center,
					contentContainerStyle,
				]}
				bounces={false}
				showsVerticalScrollIndicator={false}
			>
				{children}
			</ScrollView>
		</ActionSheet>
```

**Comment by ammarahm-ed** [comment]
This is fixed. please go through the handling safearea guide at https://rnas.vercel.app/guides/safeare.

Make sure to upgrade to v0.8.2
