### ISSUE TITLE
[0.8.3] Error when changing elements inside the Actionsheet while it's open

### ISSUE THREAD

**Issue by efstathiosntonas** [ammarahm-ed/react-native-actions-sheet#189]
Hi, I'm getting this error if the sheet is open and I change an element inside it and FastRefresh kicks in:

![simulator_screenshot_620D9296-6B2A-40E9-B837-8FA759ACF8D0](https://user-images.githubusercontent.com/717975/186383569-415364a6-57a6-4677-a8e5-3f92cdfc2967.png)

Nothing special in terms of code used, using the standard sheet with no Scrollview etc, just plain text with vector icons and a button.

using react native `0.68.4` and module version `0.8.3`

edit: If I dismiss the error it works just fine, but if I change something again, open sheet and then close it, it comes back. A full refresh fixes it until I change something the next time.  In other words, after the error shows up I dismiss the error,  every time I close the sheet it will throw error.

**Comment by efstathiosntonas** [comment]
with SheetProvider on App.tsx one step before my Routes. I have plenty of other stuff/providers above but it was never an issue on 0.8.0 (i was pulling directly from github even before you officially released 0.8.0 on npm). I think this started after 0.8.1 version.

**Comment by ammarahm-ed** [comment]
@efstathiosntonas where are you registering your sheets?

**Comment by efstathiosntonas** [comment]
with `registerSheet("bookmark_action_sheet", BookmarkedPostActionSheet)` as per README and then export it from index.ts. 

So it goes something like this: 

```tsx
const BookmarkedPostActionSheet = (props: {
  payload: { bookmark: Post_Bookmark; navigation: any };
  sheetId: string;
}) => {
  
...some other logic in here, the components inside the sheet are styled-components

  return (
    <ActionSheet
      id={props.sheetId}
      closable
      containerStyle={actionSheetContainerStyle}
      elevation={3}
      gestureEnabled
      indicatorStyle={actionSheetIndicatorStyle}
    >
      <View style={{ backgroundColor: "#E7EAEE" }}>
        <ActionSheetWrapper>
          <ActionSheetBubble>
            <ActionSheetText
              iconColor="#F86262"
              iconName="trash"
              iconSize={18}
              isDanger
              onPress={onRemovePostBookmark}
              text="Unsave"
            />
            <ActionSheetSubtitle
              iconColor="#191D23"
              iconName="stamp"
              iconSize={18}
              onPress={onReportPost}
              subtitle="This post violates Hiki’s Terms of Service."
              title="Report Post"
            />
          </ActionSheetBubble>
          <ActionSheetButton title="Close" onPress={onCloseSheet} primary />
        </ActionSheetWrapper>
      </View>
    </ActionSheet>
  );
};

registerSheet("bookmark_action_sheet", BookmarkedPostActionSheet);

export default BookmarkedPostActionSheet;

```

**Comment by ammarahm-ed** [comment]
Hmm 🤔 move the `registerSheet` function out to the `sheets.ts` file. I think that should fix this.

Also docs are updated at https://rnas.vercel.app. do check it out.

**Comment by efstathiosntonas** [comment]
@ammarahm-ed I moved everything to `sheets.ts` and it’s better now, it only throwed the error once when I was messing with flipper and Devtools. If it throws it again I’ll reopen it.

thanks

**Comment by ammarahm-ed** [comment]
**@efstathiosntonas** thanks for letting me know. 🚀
