### ISSUE TITLE
Device freezing after interacting with input inside bottom sheet.

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-actions-sheet#192]
When in a modal and opening a sheet with an input, after filling the input and closing the sheet, the app gets frozen and unresponsive.

I'm using react-native-actions-sheet v0.8.3

**Comment by ammarahm-ed** [comment]
@focux Hmm 🤔 what do you mean by interaction with input. Can you share a small example? Do you mean that it freezes on sending some api req etc after input. Or just that if you focus the input, close the sheet, the screen is frozen?

**Comment by focux** [comment]
I'm not doing any work inside the sheet, just storing a value from one input. Also, I've been testing more and the screen it's not actually frozen but it's not getting any touch event, so it looks like it's frozen, and it doesn't seem related to the input anymore, I removed all the content of the sheet and it's still happening.

I will try to reproduce it inside a snack.

**Comment by focux** [comment]
I was able to fix the bug, but I'm still not sure what was the bug, I was using the `react-native-keyboard-accessory` package and once I removed that part from the modal, it started working again. It's odd because it was working on prior versions.

**Comment by dkulakov** [comment]
I faced this issue when I had `LayoutAnimation.configureNext();` in the `useEffect`.
Once I remove it, everything works fine.
