### ISSUE TITLE
Gesture return cannot close the actions-sheet

### ISSUE THREAD

**Issue by 13627491210** [ammarahm-ed/react-native-actions-sheet#195]
Hello,  Gesture return cannot close the actions-sheet, can you help me? thanks~

**Comment by 13627491210** [comment]
closeOnTouchBackdrop ，is invalid

**Comment by ammarahm-ed** [comment]
Can you explain what you mean by that?

**Comment by n-kulic** [comment]
@ammarahm-ed `onClose` callback is not triggered when you close `ActionSheet`:

[react-native-actions-sheet](https://github.com/ammarahm-ed/react-native-actions-sheet) - **v0.8.3**

```js
<ActionSheet
  id={sheetId}
  ref={actionSheetRef}
  onClose={() => {
    console.log('CLOSE...');
  }}
  ```

Reproducible example (forked original expo snack example): https://snack.expo.dev/@nkulic/github.com-ammarahm-ed-react-native-actions-sheet:expo-example

**Comment by 13627491210** [comment]
> Can you explain what you mean by that?

sorry,my English is not good 。 please allow me speak chinese with you。

**Comment by 13627491210** [comment]
> > Can you explain what you mean by that?
> 
> sorry,my English is not good 。 please allow me speak chinese with you。

我升级了最新版“react-native-actions-sheet” 之后，手势返回和物理返回 不会关闭 sheet。0.7 is OK，but 0.8 is bad。 help me,thanks。

**Comment by ammarahm-ed** [comment]
I will look into it.

**Comment by ammarahm-ed** [comment]
Hey @13627491210 Please follow the latest guide at https://rnas.vercel.app. @n-kulic I fixed the onClose prop not getting called but that is not related to sheet not closing. Sheet closes normally in the example.

**Comment by ammarahm-ed** [comment]
Also @13627491210 Can you share a video, I think it will help me better understand what is happening.

**Comment by 13627491210** [comment]
> 还@13627491210你能分享一个视频吗，我想它会帮助我更好地了解正在发生的事情。

OK

**Comment by 13627491210** [comment]
https://user-images.githubusercontent.com/37203543/186835626-86281332-1ce8-41ef-ba88-656584e0815c.mp4

**Comment by 13627491210** [comment]
@ammarahm-ed   uploaded

**Comment by ammarahm-ed** [comment]
@13627491210 okay, The Back Handler is not working? if i am correct.

**Comment by 13627491210** [comment]
> @13627491210 okay, The Back Handler is not working? if i am correct.

yeah,  actions-sheet  is not closed。

**Comment by ammarahm-ed** [comment]
Fixed. wait for next release.

**Comment by 13627491210** [comment]
> Fixed. wait for next release.

how time release the next version? i need it 。

**Comment by 13627491210** [comment]
> Fixed. wait for next release.


> 

@ammarahm-ed

**Comment by ammarahm-ed** [comment]
Probably today.

**Comment by 13627491210** [comment]
> 

hello, The Back Handler is working，but FlatView  is not working, dont't scroll 。
