### ISSUE TITLE
Horizontal scroll support

### ISSUE THREAD

**Issue by vbylen** [ammarahm-ed/react-native-actions-sheet#196]
Hi @ammarahm-ed,

I've recorded a small video to show you the problem I'm encountering with horizontal scrolling inside the actions sheet.

https://user-images.githubusercontent.com/57633368/186810953-f7b4ee83-acfa-4530-a36c-5c8b3cfa1a90.MOV

Basically the vertical scroll is too sensitive and is firing even though we're trying to scroll horizontally.

Do you have any suggestions for how to proceed here?

Thank you!

**Comment by ammarahm-ed** [comment]
Hmm okay. Seems like a bug. I will fix it asap.

**Comment by ammarahm-ed** [comment]
Fixed! Thanks for reporting.

**Comment by vbylen** [comment]
Looking forward to the release 💯
