### ISSUE TITLE
Sheet position is off when keyboard is focused and isModal is false

### ISSUE THREAD

**Issue by bobharley** [ammarahm-ed/react-native-actions-sheet#197]
Here's an example [snack](https://snack.expo.dev/@bobharlly/test-action-sheet-keyboard)

![image](https://user-images.githubusercontent.com/25066334/186845751-323b85c3-272c-4496-990e-341b48295a06.png)

**Comment by ammarahm-ed** [comment]
Can you try `keyboardHandlerEnabled={false}` on ActionSheet. Should fix this for now. I will fix it internally for next release.

**Comment by ammarahm-ed** [comment]
Fixed this too. thanks for reporting.
