### ISSUE TITLE
onClose callback not called when ActionSheet closes

### ISSUE THREAD

**Issue by n-kulic** [ammarahm-ed/react-native-actions-sheet#198]
Description:
- onClose callback not called when ActionSheet closes

Steps to reproduce:
- video displaying the issue: https://user-images.githubusercontent.com/94164339/186859685-76e67e26-c276-4c01-a201-0c26a171d333.mp4
- reproducible sample: https://snack.expo.dev/@nkulic/github.com-ammarahm-ed-react-native-actions-sheet:expo-example?platform=ios

Version:
- [react-native-actions-sheet](https://github.com/ammarahm-ed/react-native-actions-sheet) **v0.8.3**

**Comment by SikoraKam** [comment]
Same happens to me
