### ISSUE TITLE
Interactions don't work when nesting action sheets.

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-actions-sheet#199]
I have two action sheets, one nested inside the other using providers. When I open the nested one, interactions like tapping and scrolling don't work on the action sheet in the foreground but are passed to the one in the background. So, if I scroll, the action sheet in the background scrolls, and the one in the foreground doesn't do anything. I have only tested in iOS so far.

Version: 0.8.3

**Comment by ammarahm-ed** [comment]
@focux does this happen on a sheet with `isModal` set to `false`>

**Comment by focux** [comment]
@ammarahm-ed Nope, both sheets are not setting `isModal` but using the default which I think is `true`.

**Comment by focux** [comment]
I changed `isModal` to false on the nested action sheet and when I swipe down—to close the sheet in the foreground—both sheets move at the same time.

**Comment by ammarahm-ed** [comment]
Have you set the context prop on nested SheetProvider?

**Comment by focux** [comment]
Yes, I did. Here is a reproduction of the issue: https://snack.expo.dev/@foocux/community-developed-navigators-and-libraries-%7C-react-navigation

**Comment by 13627491210** [comment]
@ammarahm-ed   V 0.8.4 how time realeae? i need it very much,thanks。

**Comment by ammarahm-ed** [comment]
I think I have fixed this. Thanks for reporting. Will release today.

**Comment by focux** [comment]
Sweet! Thank you for the fast response, as always.
