### ISSUE TITLE
Unresponsive screen after closing sheet

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-actions-sheet#20]
For some reason, if you try to scroll/tap as soon as the sheet closes, it doesn't work. It seems that even when the overlay is totally transparent, it takes some milliseconds/seconds to remove it from the screen. 

I tried reducing the `closeAnimationDuration` time but I didn't have any luck.

**Comment by ammarahm-ed** [comment]
Have you tried setting `animated` prop to false? This is happening because the ActionSheet is actually inside a modal, so after the animation is complete the modal hides usually. And since modal has its own fade animation, it takes around 300ms to close fully.

**Comment by ammarahm-ed** [comment]
@focux I have released a new version which fixes the issue. try it out and tell me if you are still facing the problem. Here it stopped.

**Comment by focux** [comment]
Sweet. It indeed fixed it. Feels so good when libraries have active maintainers, thank you so much.

**Comment by ammarahm-ed** [comment]
Open an issue if you face any problem again!
