### ISSUE TITLE
[Regression] Action sheet does not open inside a modal

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-actions-sheet#201]
There seems to be a regression in the last release (v0.8.4), the action sheet doesn't open inside a modal. Here is a reproduction of the issue: https://snack.expo.dev/@foocux/action-sheet-interaction-problem

**Comment by ammarahm-ed** [comment]
Hmm I think i noticed it too but then it started working suddenly. I will take a look.

**Comment by focux** [comment]
Awesome! Let me know if I can help.
