### ISSUE TITLE
Action sheet shrinks when keyboard shows

### ISSUE THREAD

**Issue by bobharley** [ammarahm-ed/react-native-actions-sheet#203]
This issue is actually weird because it doesn't always happen, so it's quite hard to reproduce. But I was able capture a screen recording of the issue happening.

I'm using 0.8.4

Here's the [snack](https://snack.expo.dev/@bobharlly/test-action-sheet-keyboard)
![test-keyboard](https://user-images.githubusercontent.com/25066334/187345692-a590b3b7-7bc6-4287-adee-723b32812cc5.gif)

**Comment by ammarahm-ed** [comment]
Probably a race condition in sequence of calculations. Will look into it.

**Comment by bobharley** [comment]
Also this doesn't happen when `isModal={true}` so I'll be doing that for now.

**Comment by ammarahm-ed** [comment]
Okay, thanks for the info. 🙏

**Comment by ammarahm-ed** [comment]
Try v0.8.7
