### ISSUE TITLE
Animation broken or initial position problem

### ISSUE THREAD

**Issue by ch3rn1k** [ammarahm-ed/react-native-actions-sheet#207]
Hello! Thank you for awesome lib, but I have some problems with it. Sometimes I'm getting weird bug when `ActionSheet` can't be opened. I'm using `SheetManager` with custom `context` (tested with global too - same bug):

```jsx
<ActionSheet
  id={sheetId}
  ref={sheetRef}
  gestureEnabled={true}
  CustomHeaderComponent={<SheetHeader />}
  backgroundInteractionEnabled={true}
  snapPoints={[30, 100]}
>
  ...
</ActionSheet>
```

**UPD:**
Maybe something with warning in console?
` WARN  Sending 'onAnimatedValueUpdate' with no listeners registered.`

https://user-images.githubusercontent.com/19375789/187904262-7df0c711-3d3f-481d-9e39-00377b62dd8b.mp4

**Comment by ammarahm-ed** [comment]
Where have you defined the SheetProvider. Do you get same issue with background interaction disabled?

**Comment by ch3rn1k** [comment]
> Where have you defined the SheetProvider. Do you get same issue with background interaction disabled?

1 is global without any params, wrapper for applucation
2 is inside page (this one on video)

**Comment by BooYeu** [comment]
Same issue. 0.8.3 is ok (but onClose is invalid), but 0.8.4 has some problems (It seems like the problem is that actions sheet in native stack navigator)

**Comment by ch3rn1k** [comment]
@ammarahm-ed I think something is wrong with content height calculations, so:

I have tested opening modal via `useEffect` hook on main page and it opens at bottom with **broken height**
```jsx
useEffect(() => {
  SheetManager.show('test-sheet', { context: 'test' });
}, []);
```
https://user-images.githubusercontent.com/19375789/188086424-4a5e3c0d-1f64-4a3e-ad93-afed408fc560.mp4


Then I have tested opening modal with 1 second delay and it **works fine** (watch video 2)
```jsx
useEffect(() => {
  setTimeout(() => {
    SheetManager.show('test-sheet', { context: 'test' });
  }, 1000);
}, []);
```
https://user-images.githubusercontent.com/19375789/188086507-06dfa031-71b0-4237-a408-fcd8a8a58554.mp4

**Comment by ammarahm-ed** [comment]
Hmmm 🤔 I think the height is calculated at the wrong time or too soon which causes the sheet to be of wrong size probably at the start. However it should resize automatically based on size changes. What if you give fixed height to the first View inside the sheet? And disable the timer?

**Comment by ch3rn1k** [comment]
> Hmmm 🤔 I think the height is calculated at the wrong time or too soon which causes the sheet to be of wrong size probably at the start. However it should resize automatically based on size changes. What if you give fixed height to the first View inside the sheet? And disable the timer?

Same

```jsx
<ActionSheet
  id={sheetId}
  ref={sheetRef}
  gestureEnabled={true}
  containerStyle={styles.sheetContainer}
  backgroundInteractionEnabled={true}
  closable={false}
  snapPoints={[30, 100]}
  CustomHeaderComponent={<View />}
>
  <View style={{ height: 1000 }}>
    <Text>hey</Text>
  </View>
</ActionSheet>
```

```jsx
seEffect(() => {
  SheetManager.show('test-sheet', { context: 'test' });
}, []);
```

https://user-images.githubusercontent.com/19375789/188100134-cb6c0d00-0132-46dd-b2c6-4394475d59a0.mp4

**Comment by ch3rn1k** [comment]
If I start opening sheet after **300ms timeout** - everything okay. Something with `react-navigation`, it breaks plugin animation :(

**Comment by ammarahm-ed** [comment]
@ch3rn1k you don't need to define  SheetProvider in each screen. Local SheetProviders are supposed to be used inside other ActionSheets only.

Use the global SheetProvider and define it at the earliest point in your app.

**Comment by ch3rn1k** [comment]
> @ch3rn1k you don't need to define SheetProvider in each screen. Local SheetProviders are supposed to be used inside other ActionSheets only.
> 
> Use the global SheetProvider and define it at the earliest point in your app.

If I define some sheets over global `SheetProvider` - it's going to be visible through app, but how to deal with "page only"?
I can't define at earliest point, because without `NavigationContainer` navigation function will not work (hook, etc.)

**Comment by ch3rn1k** [comment]
Well, I have tested setting global SheetProvider and got same:

App.js
```jsx
<SheetProvider>
  <NavigationContainer>
    ...
   </NavigationContainer>
</SheetProvider>
```

**Comment by ammarahm-ed** [comment]
@ch3rn1k Can you try replacing `useEffect` with `useLayoutEffect`.

**Comment by ch3rn1k** [comment]
> @ch3rn1k Can you try replacing `useEffect` with `useLayoutEffect`.

Yeah, work fine without delay but only in `global` `SheetProvider`. Any way to use local `SheetProvider` inside page?

**Comment by ammarahm-ed** [comment]
@ch3rn1k I just tested with local sheet provider + react navigation and it's working correctly for me. Can you try running the master branch?

```
yarn add https://github.com/ammarahm-ed/react-native-actions-sheet.git
```
And see if it should fix the problem or not.

Here's how I tested it:

```tsx
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import React, {useEffect} from 'react';
import {Text, View} from 'react-native';
import {SheetProvider, SheetManager} from '../';
import ExampleScreen from './src/screen';
import './src/sheets';

//@ts-ignore
function HomeScreen({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text
        style={{
          fontSize: 30,
        }}
        onPress={() => {
          navigation.navigate('Next');
        }}>
        NEXT
      </Text>
    </View>
  );
}

function NextScreen() {
  useEffect(() => {
    SheetManager.show('example-sheet', {
      payload: {data: 'hello world'},
    });
    return () => {
      SheetManager.hide('example-sheet', {
        payload: {data: 'hello world'},
      });
    };
  }, []);
  return (
    <SheetProvider>
      <View
        style={{
          flex: 1,
          width: '100%',
          alignItems: 'center',
          justifyContent: 'center',
        }}>
        <ExampleScreen />
      </View>
    </SheetProvider>
  );
}

const Stack = createNativeStackNavigator();

const App = () => {
  return (
    <>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen name="Home" component={HomeScreen} />
          <Stack.Screen name="Next" component={NextScreen} />
        </Stack.Navigator>
      </NavigationContainer>
    </>
  );
};

export default App;
```
When I move from Home to Next screen, the Sheet shows up instantly and in correct position.

**Comment by ch3rn1k** [comment]
> @ch3rn1k I just tested with local sheet provider + react navigation and it's working correctly for me. Can you try running the master branch?
> 
> ```
> yarn add https://github.com/ammarahm-ed/react-native-actions-sheet.git
> ```
> 
> And see if it should fix the problem or not.
> 
> Here's how I tested it:
> 
> ```tsx
> import {NavigationContainer} from '@react-navigation/native';
> import {createNativeStackNavigator} from '@react-navigation/native-stack';
> import React, {useEffect} from 'react';
> import {Text, View} from 'react-native';
> import {SheetProvider, SheetManager} from '../';
> import ExampleScreen from './src/screen';
> import './src/sheets';
> 
> //@ts-ignore
> function HomeScreen({navigation}) {
>   return (
>     <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
>       <Text
>         style={{
>           fontSize: 30,
>         }}
>         onPress={() => {
>           navigation.navigate('Next');
>         }}>
>         NEXT
>       </Text>
>     </View>
>   );
> }
> 
> function NextScreen() {
>   useEffect(() => {
>     SheetManager.show('example-sheet', {
>       payload: {data: 'hello world'},
>     });
>     return () => {
>       SheetManager.hide('example-sheet', {
>         payload: {data: 'hello world'},
>       });
>     };
>   }, []);
>   return (
>     <SheetProvider>
>       <View
>         style={{
>           flex: 1,
>           width: '100%',
>           alignItems: 'center',
>           justifyContent: 'center',
>         }}>
>         <ExampleScreen />
>       </View>
>     </SheetProvider>
>   );
> }
> 
> const Stack = createNativeStackNavigator();
> 
> const App = () => {
>   return (
>     <>
>       <NavigationContainer>
>         <Stack.Navigator>
>           <Stack.Screen name="Home" component={HomeScreen} />
>           <Stack.Screen name="Next" component={NextScreen} />
>         </Stack.Navigator>
>       </NavigationContainer>
>     </>
>   );
> };
> 
> export default App;
> ```
> 
> When I move from Home to Next screen, the Sheet shows up instantly and in correct position.

Well, I'm still getting same. Hope others is okay.

**Comment by prateek-somaiya** [comment]
I also have this problem, getting this `Sending 'onAnimatedValueUpdate' with no listeners registered.` warning and if I open the sheet after this warning, the height is not calculated properly, but it is intermittent, does not happen always, do we have a proper fix for this?
