### ISSUE TITLE
Opening, closing and content size calculation problem on iOS phones after 0.8.2 update.

### ISSUE THREAD

**Issue by HyopeR** [ammarahm-ed/react-native-actions-sheet#208]
Hello, I am using the new version of your package in a project I am currently developing. 
**After the [0.8.2 update](https://github.com/ammarahm-ed/react-native-actions-sheet/releases/tag/v0.8.2)**, I think there are some calculation errors when opening and closing sheet on **ios phones**. 
Sometimes everything works fine. Sometimes the **sheet opens but does not appear,** 
opens but **does not close completely** and **blocks touch actions**, etc... 
I guess the safe area guards you brought with 0.8.2 are breaking some calculations.
I tried opening the sheets both with reference and through the sheet manager and got the same result.

**Note:** I made a small patch to 0.8.1 and that's how I'm using it.
**Note 2:** I also tried it in versions 0.8.2, 0.8.3 and 0.8.4.

**Comment by ammarahm-ed** [comment]
Is this happening with backgroundInteractionsEnabled?

**Comment by HyopeR** [comment]
Yes, I tried this property, it didn't make any difference.
I'll try to provide more information when I'm available.
Thanks for this functional package. @ammarahm-ed  Cheers 🥂

**Comment by efstathiosntonas** [comment]
@ammarahm-ed I’ve also noticed that the sheet sometime opens from the top to the bottom, it feels like it starts big and then gets small or it starts from the top of the screen, it happens fast and I cannot clearly see the entry point. I don’t know about Android, haven’t tested it.

**Comment by ammarahm-ed** [comment]
This is fixed master. Will release today

**Comment by efstathiosntonas** [comment]
@ammarahm-ed any news on this? Thanks

**Comment by ammarahm-ed** [comment]
Try v0.8.7
