### ISSUE TITLE
ActionSheet shadow styles

### ISSUE THREAD

**Issue by ch3rn1k** [ammarahm-ed/react-native-actions-sheet#209]
Any way to remove/change shadow of `ActionSheet`?
I have tried to change via `containerStyle` and `style` - nothing works, thanks

```jsx
shadowColor: 'black',
shadowOffset: {
  width: 0,
  height: 4
},
shadowOpacity: 0.1,
shadowRadius: 8
``` 

![image](https://user-images.githubusercontent.com/19375789/188115941-07fd343e-71ee-4802-9e2c-8e927ee4d171.png)

**Comment by ch3rn1k** [comment]
Everyone searching - use `elevation` on `ActionSheet`, my fault

**Comment by ch3rn1k** [comment]
> This doesn't seem to be working for me. I'm trying to remove the box shadow on Android. Here is my code:
> 
> ```
> 
>       <ActionSheet
> 
>         containerStyle={{backgroundColor: 'transparent', elevation: 0 }}
> 
>         ref={actionSheetRef}
> 
>       >
> 
> ```
> 
> In the screenshot below you can see the box shadow in the background. Ideally the box shadow would be fully removed.
> 
> ![Screenshot 2023-11-13 at 2 40 03 PM](https://github.com/ammarahm-ed/react-native-actions-sheet/assets/158135/3ece5866-38c1-4791-a3f7-827c268f0565)
> 
> 

Have you tried elevation?

**Comment by noumantahir** [comment]
is there any way we can remove this shadow, the elevation property seems to only work for changing the shadow but attempting to remove the shadow does not work

any ideas

```
  containerStyle: {
    backgroundColor: 'transparent',
    paddingBottom: 12,
    shadowColor: 'transparent',
   shadowOpacity:0,
    elevation: 5,
  } as ViewStyle,
```

![Image](https://github.com/user-attachments/assets/60c6bffc-0aa3-403e-9cfc-f572fc6c978e)
![Image](https://github.com/user-attachments/assets/87a4f7bf-4089-4eec-8e2c-e058eb590cd7)
