### ISSUE TITLE
Proptype for container style does not accept array

### ISSUE THREAD

**Issue by bobdeprez** [ammarahm-ed/react-native-actions-sheet#21]
Hello,

The proptype for containerstyle does not accept an array, although it works, is it possible to adapt it so that also arrays are accepted for container style?

Im doing it like this:

<ActionSheet
      ref={actionSheetRef}
      containerStyle={[
        styles.actionSheetStyle.default,
        styles[props.colorMode].actionSheetStyle,
      ]}>

Warning: Failed prop type: Invalid prop `containerStyle` of type `array` supplied to `ActionSheet`, expected `object`.
    in ActionSheet (at DropdownSheet.js:21)
    in DropdownSheet (at ServiceTimesPage.js:73)

**Comment by ammarahm-ed** [comment]
@bobdeprez Yes, I will fix this in the next version. Thanks for reporting

**Comment by ammarahm-ed** [comment]
Seems like you are using older version of actionsheet I already fixed it in the latest version

**Comment by bobdeprez** [comment]
Hi, I have the last version, 2.6.0: "react-native-actions-sheet": "^0.2.6",

Is I look in node_modules I see for container style only the proptype object:

ActionSheet.propTypes = {
  children: PropTypes.node,
  CustomHeaderComponent: PropTypes.node,
  CustomFooterComponent: PropTypes.node,
  extraScroll: PropTypes.number,
  footerAlwaysVisible: PropTypes.bool,
  headerAlwaysVisible: PropTypes.bool,
  **containerStyle: PropTypes.object,**
  footerStyle: PropTypes.object,
