### ISSUE TITLE
Action Sheet  can not show views on ios

### ISSUE THREAD

**Issue by TangChanged** [ammarahm-ed/react-native-actions-sheet#213]
![WechatIMG395](https://user-images.githubusercontent.com/12230238/188811608-3b9aa89b-4c2e-4372-b070-ba026f55e815.png)

version: 0.8.4.

show：  customOptionRef.current?.setModalVisible(true);
onOpen has a callback but can not show views。

The image above is an ios layer. the top shows the action sheet modal， but no children.

**Comment by alialkorsani** [comment]
I fixed by downgrade to v0.8.3

**Comment by TangChanged** [comment]
> I fixed by downgrade to v0.8.3

**Comment by TangChanged** [comment]
> I fixed by downgrade to v0.8.3

I tried and I couldn't

**Comment by alialkorsani** [comment]
did you install the package using the command : 
`yarn add react-native-actions-sheet@0.8.3`

**Comment by TangChanged** [comment]
> did you install the package using the command : `yarn add react-native-actions-sheet@0.8.3`
package.json config.: ^0.8.3, Automatic updates

**Comment by ArietNyshanbaev** [comment]
Downgrading helped me first day but on very next day it stop working again,
I still use 0.8.3 according to package-lock.json, but action sheet is invisible.
Any idea?
