### ISSUE TITLE
Keyboard avoiding behavior not smooth.

### ISSUE THREAD

**Issue by coryschadt** [ammarahm-ed/react-native-actions-sheet#218]
I have based my sheet off one of the examples here: https://snack.expo.dev/@ammarahmed/github.com-ammarahm-ed-react-native-actions-sheet:expo-example

When I tap on an input, they keyboard opens but it is not smooth like in the example (Keyboard appears, sheets animates up). 
In mine, there is a bit of a delay, the keyboard appears and the modal doesn't animate up. I tested this in the simulator and a device.

"react-native": "0.70.0",
"react-native-actions-sheet": "^0.8.7",

https://user-images.githubusercontent.com/682876/190770925-1b02d5f8-78f4-446c-8bec-26875c5b8c1c.mov

**Comment by bencreynolds** [comment]
I have the same issue. Hopefully the developer responds.

**Comment by coryschadt** [comment]
> I have the same issue. Hopefully the developer responds.

@bencreynolds it works, just a little janky. Be great to smooth that out. otherwise this is an awesome solution so far.

**Comment by bencreynolds** [comment]
Just tested, looks like the "jerky" behavior started in 0.8.4. It worked normally before then.

**Comment by coryschadt** [comment]
> Just tested, looks like the "jerky" behavior started in 0.8.4. It worked normally before then.

You are right! 
https://user-images.githubusercontent.com/682876/191815415-44bbb4c8-9166-446f-885c-cdfea4d2b2dc.mov

**Comment by ammarahm-ed** [comment]
I worked a solution to fix this and some other issues with keyboard. Will make a new release soon.

**Comment by coryschadt** [comment]
> I worked a solution to fix this and some other issues with keyboard. Will make a new release soon.

Thank you! I tried to send a small sponsorship via paypal: got this message FYI "Sorry, this recipient can’t accept payments right now."

**Comment by bencreynolds** [comment]
> I worked a solution to fix this and some other issues with keyboard. Will make a new release soon.

Awesome! Thanks so much :)

**Comment by ammarahm-ed** [comment]
> > I worked a solution to fix this and some other issues with keyboard. Will make a new release soon.
> 
> Thank you! I tried to send a small sponsorship via paypal: got this message FYI "Sorry, this recipient can’t accept payments right now."

I should probably remove that. We don't have PayPal in my country. It's technically impossible to get a donation in a simple way.

**Comment by johnny-mcfadden-dailypay** [comment]
@coryschadt or anyone here, how did you get the slide down animation? Upgraded to `0.8.7` and the action sheets seem to just fadeout on backdrop press and calling hide action sheet.

**Comment by bencreynolds** [comment]
> @coryschadt or anyone here, how did you get the slide down animation? Upgraded to `0.8.7` and the action sheets seem to just fadeout quite abruptly on backdrop press and calling hide action sheet.

I haven’t had that issue with 0.8.7. Dismiss behavior doesn’t change between versions for me. I’d need to see your code to be of any help.

**Comment by johnny-mcfadden-dailypay** [comment]
Sorry it was me being silly with a close animation override for the spring speed 🤦. thanks.

**Comment by ammarahm-ed** [comment]
Hi, try v0.8.8. It adds animations for keyboard open/close.

**Comment by jagl-epam** [comment]
> > Hi, try v0.8.8. It adds animations for keyboard open/close.
> 
> Thank you. I now get this error upon updating to V0.8.8
> 
>  Screen.Recording.2022-10-11.at.9.05.05.AM.mov

Hi @coryschadt 

I just now had this issue, happens that the library handles the padding bottom from the containerStyle, if you have added it to your code, you have to provide either a paddingBottom > 1 or a padding of >=0

Here is the line where this behaviour happens, if you add a paddingBottom = 0, its a nullish value and then retrieves the padding (this being undefined), and the whole app crashes due a NaN issue. 

https://github.com/ammarahm-ed/react-native-actions-sheet/blob/1b01954657c20c121c85c11933e2ee5beb60bfe1/src/index.tsx#L805

**Comment by ammarahm-ed** [comment]
Fixed
