### ISSUE TITLE
Actions sheet closes on first open

### ISSUE THREAD

**Issue by jeanlucdu55** [ammarahm-ed/react-native-actions-sheet#22]
Hi, 

Thanks for the library, really appreciated! 

I have a small issue, when I open the library for the first time, it closes automatically, then on the second time it works fine, any idea why? 

Thanks, 

Théo

**Comment by ammarahm-ed** [comment]
@jeanlucdu55 are you facing this issue on Android or iOS?

**Comment by ammarahm-ed** [comment]
use the `delayActionSheetDraw`& `delayActionSheetDrawTime` prop to handle this
