### ISSUE TITLE
Broken scrollHandlers

### ISSUE THREAD

**Issue by ch3rn1k** [ammarahm-ed/react-native-actions-sheet#220]
After changing `key` prop on `ScrollView/FlatList` breaks scrollHandlers. Any idea how to fix that?

**Comment by johnny-mcfadden-dailypay** [comment]
@ch3rn1k could you provide more information? I was also trying to use the scroll handlers for an action sheet with a scrollview inside but wasn't having any luck. I resorted to disabled gestures for an action sheet with lots of vertical content to get the scroll working.

**Comment by ch3rn1k** [comment]
> @ch3rn1k could you provide more information? I was also trying to use the scroll handlers for an action sheet with a scrollview inside but wasn't having any luck. I resorted to disabled gestures for an action sheet with lots of vertical content to get the scroll working.

@ammarahm-ed 
Well, problem is still there. After changing `key` prop `scrollHandlers` stop working

```
const appState = useAppState();
const scrollHandlers = useScrollHandlers('scrollview', sheetRef);

return (
  <FlatList
      numColumns={appState.searchView === 'grid' ? 2 : 1}
      data={data}
      renderItem={(value) => (....)}
      key={appState.searchView}
      {...scrollHandlers}
    />
);
```
