### ISSUE TITLE
useScrollHandlers isn't allowing me to scroll

### ISSUE THREAD

**Issue by NathanC** [ammarahm-ed/react-native-actions-sheet#225]
I'm using 0.8.7, and have a ScrollView in my ActionsSheet. I followed the guide, and set up the handler like this:

```tsx
 const actionSheetRef = useRef<ActionSheetRef>(null);

    const scrollHandlers = useScrollHandlers<ScrollView>(
      'scrollview-1',
      actionSheetRef,
    );
```

Then my action sheet like this:
```tsx
  <ActionSheet ref={actionSheetRef} gestureEnabled containerStyle={{backgroundColor: midnightBlue, height: 350, borderTopLeftRadius: 20, borderTopRightRadius: 20}}>
            <ScrollView  {...scrollHandlers}>
```

It renders the ActionSheet, but I can't scroll to the bottom of my list. Swiping up just kicks in the overscroll effect. Swiping down closes the ActionSheet, but is a little unreliable/sometimes laggy.

I'm using Expo Go in Android 13.

Any ideas? I like this library a lot, but right now this is preventing me from using it.

**Comment by NathanC** [comment]
Also, something that may be good to support (and was the behavior of the actionsheet I was using previously) would be gesture enabled only on the little handle on the top. That would support ScrollView nicely, even though it's not ideal.

**Comment by monk-lee** [comment]
same issue + 1

Scrolls do not work properly on both iPhone, Android, and Expo.

**Comment by ammarahm-ed** [comment]
@monk-lee @NathanC Right now ScrollView/FlatList behavior is not ideal. It sometimes works & sometimes does not. One workaround is to wrap your renderItem in a button such as a Touchable/Pressable which makes the ScrollView work in most cases. If it's a ScrollView, wraps item inside it in TouchableOpacity & set activeOpacity to 1.

I am looking for a better solution. Yet to find one.

**Comment by kikikiswanto** [comment]
work for me, i use FlatList instead ScrollView.

**Comment by natemartins** [comment]
> work for me, i use FlatList instead ScrollView.

@kikikiswanto How did you achieve that since it's not recommended to have virtualist inside of a scrollview. This error specifically says so:

`VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead`

**Comment by MindthemediaDev** [comment]
Just a heads up to anyone experiencing this issue. I fixed the problem by wrapping the components in <ScrollView> with <Pressable> that seems to fix the issue.
Something like this: 
`<ScrollView  ref={scrollViewRef} {...scrollHandlers} style={styles.scrollview} >
    <Pressable>
        /*...*/
    </Pressable>
</ScrollView>`

**Comment by quantran-epi** [comment]
same issue + 1 
any updates on this?

**Comment by trne** [comment]
this is not fixed by #330 
I'm on version `0.9.2` and still having major issues when using a scroll view on an action sheet on android.

**Comment by jonxssc** [comment]
> this is not fixed by #330 
> 
> I'm on version `0.9.2` and still having major issues when using a scroll view on an action sheet on android.

Try to use the scrollview from the package, then it should work, only with zhe scrollhandler it doesnt really work:
`import ActionSheet, {ScrollView, FlatList} from 'react-native-actions-sheet';
 
const ExampleSheet = () => {
  return (
    <ActionSheet>
      <ScrollView />
    </ActionSheet>
  );
}; `

**Comment by trne** [comment]
> ScrollView

this works, thanks for sharing @jonxssc 
the `scrollHandler` still outstanding, though.

**Comment by mustafa695** [comment]
> ScrollView

Working for me.

**Comment by MikeyRG127** [comment]
After some serious trial and error, here’s how to get this working properly:

```
import ActionSheet, { ScrollView, FlatList } from 'react-native-actions-sheet';

const ExampleSheet = () => {
  return (
    <ActionSheet>
      <ScrollView>
        {/* All the content you want to be scrollable */}
      </ScrollView>
    </ActionSheet>
  );
};
```

🚫 Important: Don’t use ScrollView or FlatList from React Native directly inside <ActionSheet> — it won’t behave correctly.
✅ Instead, use the versions exported by react-native-actions-sheet, or use .map() if you're rendering a list of items.
