### ISSUE TITLE
When typing in Action Sheet, close the keyboard the bottom part of action sheet disappear for a few moment

### ISSUE THREAD

**Issue by adrian3ka** [ammarahm-ed/react-native-actions-sheet#229]
https://user-images.githubusercontent.com/31057437/194734536-d1b98b88-a8cd-416c-8889-f3f281e473b6.MP4

When we have Text Input inside the Action Sheet, we have a blink for a moment for the backdrop keyboard. 
It's only happening when the text input is inside the action sheet.

> <ActionSheet
  id={sheetId}
  isModal={false}
  zIndex={zIndex}
  containerStyle={{
    height: '99%',
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  }}
>

**Comment by ammarahm-ed** [comment]
Can you try 0.8.8

**Comment by chazzaoui** [comment]
Also experiencing the issue with version 0.8.8

https://user-images.githubusercontent.com/22476835/196496918-cdcaabd0-ab3a-4cc7-8da9-0b4541a54e0d.MOV

**Comment by Roka20012** [comment]
@ammarahm-ed I see similar behavior in the expo snack demo
When opening the keyboard on the example sheet with input, the sheet is jumping

I really like this lib, would you happen to have any plans to fix some issues with the keyboard?

https://snack.expo.dev/@ammarahmed/github.com-ammarahm-ed-react-native-actions-sheet:expo-example

**Comment by Roka20012** [comment]
@ammarahm-ed this is what pointed out when the sheet is not fully open keyboard handling is okay, but when it's fully opened it's jumping

https://user-images.githubusercontent.com/32239452/223034440-116302b0-f41c-46ed-84a5-45a48ceda3c7.mov

**Comment by Engazan** [comment]
> @ammarahm-ed this is what pointed out when the sheet is not fully open keyboard handling is okay, but when it's fully opened it's jumping
> 
>  Screen.Recording.2023-03-06.at.08.22.31.mov

i fixes that by wrapping ``ActionSheet`` into my own component and adding listener for ``keyboardWillShow`` event then changing ``minHeight`` of ``ActionSheet`` to + 520 to avoid this jumps 

video preview (wrong state and fixed state)


https://github.com/ammarahm-ed/react-native-actions-sheet/assets/53254371/fb2670c1-7c47-4a25-9653-a47a528ee76b


same issue is with ``keyboardWillHide`` state, same fix just change some styles when this event triggers, hope @ammarahm-ed will fix it

btw i m using ``"react-native-actions-sheet": "^0.8.29",``

small wrapper example
```tsx
interface ActionSheetWrapperRef {
    show: () => void;
    hide: () => void;
}

interface ActionSheetWrapperProps {
    ref: React.Ref<ActionSheetWrapperRef>;
    children: React.ReactNode;
    id?: string;
    containerStyle?: ActionSheetProps['containerStyle'];
    onClose?: ActionSheetProps['onClose'];
}

const ActionSheetWrapper: React.FC<ActionSheetWrapperProps> = React.forwardRef((props, forwardedRef) => {

    const insets = useSafeAreaInsets();

    const actionSheetRef = React.useRef<ActionSheetRef>(null);
    const [isKeyboardShowing, setIsKeyboardShowing] = React. useState(false);

    React.useImperativeHandle(forwardedRef, () => ({
        show: () => actionSheetRef.current?.show(),
        hide: () => actionSheetRef.current?.hide(),
    }), []);

    React.useEffect(() => {
        const keyboardWillShowListener = Keyboard.addListener(
            'keyboardWillShow',
            () => {
                setIsKeyboardShowing(true);
            }
        );
        const keyboardDidShowListener = Keyboard.addListener(
            'keyboardDidShow',
            () => {
                setIsKeyboardShowing(false);
            }
        );

        return () => {
            keyboardWillShowListener.remove();
            keyboardDidShowListener.remove();
        };
    });

    return (
        <ActionSheet
            id={props?.id ?? 'ActionSheetWrapper-' + Math.random()}
            ref={actionSheetRef}
            containerStyle={{
                ...getDefaultActionSheetStyle(insets),
                ...props.containerStyle,
                ...{
                    minHeight: getMinActionSheetHeight() + (isKeyboardShowing ? 520 : 0),
                },
            }}
            onClose={props.onClose}
        >
            {props.children}
        </ActionSheet>
    )
});
```

**Comment by ammarahm-ed** [comment]
> > @ammarahm-ed this is what pointed out when the sheet is not fully open keyboard handling is okay, but when it's fully opened it's jumping
> > 
> >  Screen.Recording.2023-03-06.at.08.22.31.mov
> 
> i fixes that by wrapping ``ActionSheet`` into my own component and adding listener for ``keyboardWillShow`` event then changing ``minHeight`` of ``ActionSheet`` to + 520 to avoid this jumps 
> 
> video preview (wrong state and fixed state)
> 
> 
> https://github.com/ammarahm-ed/react-native-actions-sheet/assets/53254371/fb2670c1-7c47-4a25-9653-a47a528ee76b
> 
> 
> same issue is with ``keyboardWillHide`` state, same fix just change some styles when this event triggers, hope @ammarahm-ed will fix it
> 
> btw i m using ``"react-native-actions-sheet": "^0.8.29",``
> 
> small wrapper example
> ```tsx
> interface ActionSheetWrapperRef {
>     show: () => void;
>     hide: () => void;
> }
> 
> interface ActionSheetWrapperProps {
>     ref: React.Ref<ActionSheetWrapperRef>;
>     children: React.ReactNode;
>     id?: string;
>     containerStyle?: ActionSheetProps['containerStyle'];
>     onClose?: ActionSheetProps['onClose'];
> }
> 
> const ActionSheetWrapper: React.FC<ActionSheetWrapperProps> = React.forwardRef((props, forwardedRef) => {
> 
>     const insets = useSafeAreaInsets();
> 
>     const actionSheetRef = React.useRef<ActionSheetRef>(null);
>     const [isKeyboardShowing, setIsKeyboardShowing] = React. useState(false);
> 
>     React.useImperativeHandle(forwardedRef, () => ({
>         show: () => actionSheetRef.current?.show(),
>         hide: () => actionSheetRef.current?.hide(),
>     }), []);
> 
>     React.useEffect(() => {
>         const keyboardWillShowListener = Keyboard.addListener(
>             'keyboardWillShow',
>             () => {
>                 setIsKeyboardShowing(true);
>             }
>         );
>         const keyboardDidShowListener = Keyboard.addListener(
>             'keyboardDidShow',
>             () => {
>                 setIsKeyboardShowing(false);
>             }
>         );
> 
>         return () => {
>             keyboardWillShowListener.remove();
>             keyboardDidShowListener.remove();
>         };
>     });
> 
>     return (
>         <ActionSheet
>             id={props?.id ?? 'ActionSheetWrapper-' + Math.random()}
>             ref={actionSheetRef}
>             containerStyle={{
>                 ...getDefaultActionSheetStyle(insets),
>                 ...props.containerStyle,
>                 ...{
>                     minHeight: getMinActionSheetHeight() + (isKeyboardShowing ? 520 : 0),
>                 },
>             }}
>             onClose={props.onClose}
>         >
>             {props.children}
>         </ActionSheet>
>     )
> });
> ```

Can you try the latest alpha release?

**Comment by Engazan** [comment]
> Can you try the latest alpha release?

@ammarahm-ed  i changed version to ``^0.9.0-alpha.24`` and its still happening

looks like "keyboardAnimation()" is called after keyboard is fully visible :/
