### ISSUE TITLE
 Invariant Violation: [4633,"RCTView",{"paddingBottom":"<<NaN>>"}] is not usable as a native method argument

### ISSUE THREAD

**Issue by ayuleul** [ammarahm-ed/react-native-actions-sheet#231]
**Description**
The error occurs when I try to write on the text input after upgrading to 0.8.8 to resolve issue #224. Version 0.8.7 worked flawlessly.

**Error**
![new](https://user-images.githubusercontent.com/36878262/197325561-29a281b9-fd3c-4313-a2e5-6810e2538fb6.png)
![new 2](https://user-images.githubusercontent.com/36878262/197325564-52d773e5-1e2a-4dcd-bdbf-aea5fa714e95.png)
![new 3](https://user-images.githubusercontent.com/36878262/197325567-a99f7e86-84e5-41bf-8bdb-c29f859e3de3.png)

 
**Additional Information**
- [react-native-actions-sheet: 0.8.8
- React Native version: 0.69.4
- Platform: Android, not sure for IOS
- Development Operating System: Window 11
- Hermes enabled

**Sample code**

```
 <ActionSheet/>
  id="feed-create-post-sheet"
  ref={actionSheetRef}
  containerStyle={styles.actionContainer}
  statusBarTranslucent
  drawUnderStatusBar={true}
  defaultOverlayOpacity={0.3}
  gestureEnabled={true}>
  <View style={styles.container}>
    <View style={styles.inputConStyle}>
        <TextInput
          value={message}
          onChangeText={handleMessageChange}
          multiline
          style={styles.input}
        />
    </View>
    <Button
      onPress={handle}
    />
  </View>
</ActionSheet>
```

**Comment by SeeJ** [comment]
Confirm. Same behavior

**Comment by efstathiosntonas** [comment]
@ammarahm-ed this persists on `0.8.9`, this is the `containerStyle` prop, (it's a memoized hook)

```jsx
 const actionSheetContainerStyle = useStyle(
    () => ({
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      backgroundColor: themeContext.actionSheet.background,
    }),
    [themeContext]
  );
```

If i add `paddingBottom: 1` the error goes away but then I the bottom sheet will open with a padding equal to the keyboard height, this happens with or without the `useBottomSafeAreaPadding` prop. See the attached video at the bottom.

I've applied the styling directly to the prop (without the memo hook) and it's the same. If keyboard is open then it throws this the moment I open the sheet: 

```bash
[[103,103,103,103,103,103,103,103,103,103,103,129],[5,3,5,3,5,3,5,3,5,3,5,16],[[6955,"RCTText",21,{"isHighlighted":false,"ellipsizeMode":"tail","accessible":true,"selectionColor":null,"maxFontSizeMultiplier":1.1,"allowFontScaling":true,"fontWeight":"600","fontSize":18,"fontFamily":"System","color":4294967295}],[6955,[6953]],[6957,"RCTView",21,{"flexDirection":"row","justifyContent":"space-around","alignItems":"center"}],[6957,[6955]],[6959,"RCTView",21,{"paddingBottom":0,"paddingRight":20,"marginBottom":20,"marginTop":12,"justifyContent":"center","alignItems":"center","flexDirection":"row","opacity":1,"height":40,"accessible":true,"backgroundColor":4278290503,"paddingLeft":20,"marginRight":26,"alignSelf":"center","borderRadius":29,"collapsable":false,"width":"90%","paddingTop":0,"accessibilityRole":"button","marginLeft":26,"borderColor":0,"accessibilityHint":"tap to close bottom sheet","accessibilityLabel":"Close"}],[6959,[6957]],[6963,"RNGestureHandlerButton",21,{"collapsable":false,"exclusive":true,"enabled":true}],[6963,[6959]],[6965,"RCTView",21,{"marginTop":10,"marginBottom":6,"backgroundColor":4280558628}],[6965,[6869,6917,6949,6963]],[4977,"onTransitionProgress",349]],10918]
```



ps. i've deleted `yarn.lock` and `node_modules` and reinstalled everything.


demo video: https://www.veed.io/view/75fe3a04-8d15-4ecf-b051-42844fab6d59

**Comment by efstathiosntonas** [comment]
unrelated to this issue but 0.8.9 introduced another regression, the action sheet won't show on some of my components, I have to click the button multiple times. The video above opens the sheet instantly because actionsheet lives inside that component, the components having the issue are the ones that live in the main sheets.tx. Downgrading to 0.8.8 fixes it.

sorry for the offtopic.

**Comment by ammarahm-ed** [comment]
I will check why it's happening, can you drop your sheets.ts & one of the sheet component that fails to open so I can take a look.

**Comment by efstathiosntonas** [comment]
@ammarahm-ed pretty basic stuff as per README, nothing special. 

`sheets.tsx`

```tsx
import MatchTabReportProfileActionSheetMain from "@components/ActionSheets/MatchTabReportProfileActionSheetMain";

registerSheet("match_report_action_sheet_main", MatchTabReportProfileActionSheetMain);



export {};
```

`ActionSheet` component: 

```tsx
import ActionSheetBubble from "@components/CustomActionSheet/ActionSheetBubble";
import ActionSheetButton from "@components/CustomActionSheet/ActionSheetButton";
import ActionSheetText from "@components/CustomActionSheet/ActionSheetText/ActionSheetText";
import ActionSheetWrapper from "@components/CustomActionSheet/ActionSheetWrapper";
import React, { useCallback } from "react";
import ActionSheet, { SheetManager } from "react-native-actions-sheet";
import { useStyle } from "react-native-style-utilities";
import { Profile, useAdminMarkUserMutation } from "@generated/graphql";
import { breadcrumb, notify, showErrorAlert } from "@utils/utils";
import { fullScreenAlert } from "@components/FullScreenAlert";
import useThemeContext from "@themes/themeContext";

const MatchTabReportProfileActionSheetMain = (props: {
  payload: {
    navigation: any;
    onIgnoreUser: (shouldMarkAsIgnore: boolean) => Promise<void>;
    profile: Profile;
  };
  sheetId: string;
}) => {
  const themeContext = useThemeContext();

  const [adminMarkProfile] = useAdminMarkUserMutation();

  const actionSheetContainerStyle = useStyle(
    () => ({
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      backgroundColor: themeContext.actionSheet.background
    }),
    [themeContext]
  );
  const actionSheetIndicatorStyle = useStyle(
    () => ({
      backgroundColor: themeContext.actionSheet.indicatorColor
    }),
    [themeContext]
  );

  const onCloseSheet = useCallback(async () => {
    await SheetManager.hide("match_report_action_sheet_main");
  }, []);

  const onReportUser = useCallback(async () => {
    await onCloseSheet();
    await SheetManager.show("match_report_action_sheet", {
      payload: {
        profile: props.payload.profile,
        navigation: props.payload.navigation,
        onIgnoreUser: props.payload.onIgnoreUser
      }
    });
  }, [
    onCloseSheet,
    props.payload.navigation,
    props.payload.onIgnoreUser,
    props.payload.profile
  ]);


  return (
    <ActionSheet
      closable
      containerStyle={actionSheetContainerStyle}
      elevation={3}
      gestureEnabled
      id={props.sheetId}
      indicatorStyle={actionSheetIndicatorStyle}
    >
      <ActionSheetWrapper>
        <ActionSheetBubble>
          <ActionSheetText
            iconColor={themeContext.actionSheet.iconColor}
            iconName="triangle-exclamation"
            iconSize={16}
            onPress={onReportUser}
            text="Report User"
          />
        </ActionSheetBubble>
        <ActionSheetButton title="Close" onPress={onCloseSheet} primary />
      </ActionSheetWrapper>
    </ActionSheet>
  );
};

export default MatchTabReportProfileActionSheetMain;

```

button that opens it:

```tsx
  const onPressMore = useCallback(
    async (profile: Profile) => {
      await SheetManager.show("match_report_action_sheet_main", {
        payload: { navigation, profile, onIgnoreUser }
      });
    },
    [navigation, onIgnoreUser]
  );
```

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed this persists on `0.8.9`, this is the `containerStyle` prop, (it's a memoized hook)
> 
> ```jsx
>  const actionSheetContainerStyle = useStyle(
>     () => ({
>       borderTopLeftRadius: 20,
>       borderTopRightRadius: 20,
>       backgroundColor: themeContext.actionSheet.background,
>     }),
>     [themeContext]
>   );
> ```
> 
> If i add `paddingBottom: 1` the error goes away but then the bottom sheet will open with a padding equal to the keyboard height, this happens with or without the `useBottomSafeAreaPadding` prop. See the attached video at the bottom, when it crashed I've changed the `paddingBottom` to `0`.
> 
> I've applied the styling directly to the prop (without the memo hook) and it's the same. If keyboard is open then it throws this the moment I open the sheet: 
> 
> ```bash
> [[103,103,103,103,103,103,103,103,103,103,103,129],[5,3,5,3,5,3,5,3,5,3,5,16],[[6955,"RCTText",21,{"isHighlighted":false,"ellipsizeMode":"tail","accessible":true,"selectionColor":null,"maxFontSizeMultiplier":1.1,"allowFontScaling":true,"fontWeight":"600","fontSize":18,"fontFamily":"System","color":4294967295}],[6955,[6953]],[6957,"RCTView",21,{"flexDirection":"row","justifyContent":"space-around","alignItems":"center"}],[6957,[6955]],[6959,"RCTView",21,{"paddingBottom":0,"paddingRight":20,"marginBottom":20,"marginTop":12,"justifyContent":"center","alignItems":"center","flexDirection":"row","opacity":1,"height":40,"accessible":true,"backgroundColor":4278290503,"paddingLeft":20,"marginRight":26,"alignSelf":"center","borderRadius":29,"collapsable":false,"width":"90%","paddingTop":0,"accessibilityRole":"button","marginLeft":26,"borderColor":0,"accessibilityHint":"tap to close bottom sheet","accessibilityLabel":"Close"}],[6959,[6957]],[6963,"RNGestureHandlerButton",21,{"collapsable":false,"exclusive":true,"enabled":true}],[6963,[6959]],[6965,"RCTView",21,{"marginTop":10,"marginBottom":6,"backgroundColor":4280558628}],[6965,[6869,6917,6949,6963]],[4977,"onTransitionProgress",349]],10918]
> ```
> 
> 
> 
> ps. i've deleted `yarn.lock` and `node_modules` and reinstalled everything.
> 
> 
> demo video: https://www.veed.io/view/75fe3a04-8d15-4ecf-b051-42844fab6d59 (simluator, iphone 13 iOS 16.0)

The issue somehow related to keyboard being opened before opening actionsheet I think. 🤔 Also i think sheet is taking keyboard open param on launch and putting in wrong height when padding set to 1. when it should not.

**Comment by efstathiosntonas** [comment]
I ll dismiss the keyboard and add a 200ms timeout prior opening the sheet and see the outcome

**Comment by efstathiosntonas** [comment]
@ammarahm-ed if I dismiss keyboard and add a timeout then the action sheet opens just fine, without bottom padding. So it seems that we have a race condition here as you described in this [comment](https://github.com/ammarahm-ed/react-native-actions-sheet/issues/231#issuecomment-1290884921)

```
  const onPressMoreButton = useCallback(() => {
    dismiss();
    sleep(600).then(() => SheetManager.show("chat_room"));
  }, []);
```

**Comment by ammarahm-ed** [comment]
I think I was able to fix both issues there. the sheet not showing is iOS only. I will push changes a release a new version. And yes it's a race condition.

**Comment by efstathiosntonas** [comment]
Thank you @ammarahm-ed! Keep it up!

**Comment by efstathiosntonas** [comment]
works as a charm on `0.8.10`

**Comment by efstathiosntonas** [comment]
@ammarahm-ed if the keyboard is open and the sheet opens, if the button is navigating to another screen then the keyboard appears for a fraction of the second. 

1. Open keyboard
2. Tap button to open sheet
3. Keyboard hides
4. Tap a button inside the action sheet and navigate to another screen
5. Action sheet hides
6. New screen enters
7. Keyboard shows up
8. Keyboard hides when the navigation interaction is complete

please note that the flatlist has `keyboardShouldPersistTaps="handled"`, don’t know if it matters though.

Demo video:
https://user-images.githubusercontent.com/717975/198047156-a831b8b0-da17-4e34-962a-35f50ac74112.MOV

**Comment by ammarahm-ed** [comment]
@efstathiosntonas That's not a bug, when sheet/modal closes, the existing input gets focused again by react native and it restores the state in which the modal was opened, i.e keyboard opened. Then as you navigate, it tries to close it down and navigate.
