### ISSUE TITLE
How to make action sheet to appear above bottom tab

### ISSUE THREAD

**Issue by rawatnaresh** [ammarahm-ed/react-native-actions-sheet#232]
I'm using bottom tabs in my application and I would like to make the action sheet to appear above the bottom tabs. is there any way to achieve this?

![Screen Shot 2022-10-22 at 08 20 50](https://user-images.githubusercontent.com/29520305/197315352-9780c8d6-ce44-4691-a722-537024e80c75.png)

**Comment by rawatnaresh** [comment]
Never mind. I had to move `SheetProvider` inside bottom tab and apply `bottomPadding`  to `containerStyle` of action sheet.

**Comment by johnny-mcfadden-dailypay** [comment]
@rawatnaresh could you close this issue for the maintainer.
