### ISSUE TITLE
can't open sheet with SheetManager / SheetProvider

### ISSUE THREAD

**Issue by jjrise** [ammarahm-ed/react-native-actions-sheet#234]
I've used actions sheet for a few months now on a previous project. Today I have been setting up a new project and cannot figure out why the SheetManger isn't working.

If I open the sheet with ActionSheets directly by calling the .ref it opens fine, but not using SheetManager.

See the snack below:

https://snack.expo.dev/@jordanrising/actions-sheet-manager-not-opening

Thanks!

**Comment by jjrise** [comment]
by the way, this library has been amazing. Zero dependencies and the SheetManager is a great way to use this across an app. You guys are the best!

**Comment by ammarahm-ed** [comment]
Hey, is it happening on iOS or android?

**Comment by jjrise** [comment]
> Hey, is it happening on iOS or android? 

iOS is what I've been testing so far.

**Comment by efstathiosntonas** [comment]
@ammarahm-ed maybe related to https://github.com/ammarahm-ed/react-native-actions-sheet/issues/231#issuecomment-1290035488?

**Comment by ammarahm-ed** [comment]
Hey guys, I was able fix this, i added a `setTimeout` which had incorrect sequence of statements causing the sheet to never show up through the sheet manager.

**Comment by ammarahm-ed** [comment]
@efstathiosntonas Try v0.8.10. It should fix both issues.

**Comment by efstathiosntonas** [comment]
@ammarahm-ed thank you, it's working as a charm on `0.8.10`
