### ISSUE TITLE
keep the sheet open while gestureEnabled={true} and closeable={true}

### ISSUE THREAD

**Issue by jjrise** [ammarahm-ed/react-native-actions-sheet#235]
I need to be able to close the bottom sheet when I navigate to different screens, so I use the prop `closeable={true}`, but I do not want the user to be able to close the sheet with a bottom swipe gesture. I need to keep `gestureEnabled={true}` because it still needs to be resized to different snapPoints. 

I am using the Action Sheet with SheetManager...

How can I remove the closing gesture? This would be similar to the prop `enablePanDownToClose` in other similar libraries.

Thanks!

```js
    <ActionSheet
      initialSnapIndex={1}
      snapPoints={[30, 70, 100]}
      backgroundInteractionEnabled
      closeOnPressBack={false}
      closeOnTouchBackdrop={false}
      closable
      gestureEnabled
      containerStyle={{
        backgroundColor: colors.midGray,
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
      }}
      indicatorStyle={{
        backgroundColor: colors.lightGray,
        width: 100,
      }}
      id={props.sheetId}
    >
```

**Comment by ammarahm-ed** [comment]
@jjrise Set closable to false, so when you swipe down, sheet will go down to lowest snap point but not close. When user navigates, you can programmatically close the sheet with `SheetManager`.

**Comment by jjrise** [comment]
If I set closable to false, I cannot programmatically close it with SheetManager as it persists even when calling hide().

**Comment by ammarahm-ed** [comment]
@jjrise Seems to be a bug or missing feature, probably need to add a prop `closeOnSwipeDown` or something to prevent closing only with gestures but keep it functional otherwise.

**Comment by rayoverweij** [comment]
+1, this would be really good to have!

**Comment by randomittin** [comment]
@ammarahm-ed — is this fixed? Seems to be causing trouble with gestureEnabled={true} and closeable={true}.
