### ISSUE TITLE
Big Delay when opening ActionSheet

### ISSUE THREAD

**Issue by jonxssc** [ammarahm-ed/react-native-actions-sheet#240]
When opening an Actionsheet it has a massive delay. After 1 Second the animation starts, but it should start instant.
Running an console.log onOpen shows, that it fires instant, but the animation starts about 1 Second later.

I tried changing the openAnimationConfig but didnt achive to remove the delay. Also if i remove all the content in my ActionSheet, there is this delay.

Has anyone this problem too? I am opening my Actionsheets with an SheetManager.

**Comment by johnny-mcfadden-dailypay** [comment]
I've not had any experience of this delay, everything is super snappy.

**Comment by AlexAlexandre** [comment]
Same problem here, any solution ? 

here some more info... 

I created a Provider inside `App.tsx`  and imported the register:

```
...

import './registerActionSheet';

... 

<NavigationContainer>
      <SheetProvider>
        <AuthProvider>
          <Routes />
          <Toast />
        </AuthProvider>
      </SheetProvider>
</NavigationContainer>
```

my register: 

```
import { registerSheet } from 'react-native-actions-sheet';
import FeedbackActionSheet from './screens/Feedback/feedbackActionSheet';

registerSheet('feedbackActionSheet', FeedbackActionSheet);

export {};
```

and opened inside a touchable with `SheetManager`: 

```
<TouchableOpacity onPress={() => SheetManager.show('feedbackActionSheet')}>
          <Icon name='plus' size={20} color={colors.primary} />
</TouchableOpacity>
```

**Comment by jonxssc** [comment]
> Same problem here, any solution ?
> 
> here some more info...
> I fixed my problem adding `gestureEnabled` props

How did this fix the delay problem and where did you added the „gestureenabled“?

**Comment by AlexAlexandre** [comment]
> > Same problem here, any solution ?
> > here some more info...
> > I fixed my problem adding `gestureEnabled` props
> 
> How did this fix the delay problem and where did you added the „gestureenabled“?

To be honest with you, I really don't know if it's linked, but after that my problem was resolved. 

```
<ActionSheet id='feedbackActionSheet' ref={feedbackActionSheetRef} gestureEnabled>
...
</ActionSheet>
```

**Comment by jonxssc** [comment]
> > > Same problem here, any solution ?
> > > here some more info...
> > > I fixed my problem adding `gestureEnabled` props
> > 
> > 
> > How did this fix the delay problem and where did you added the „gestureenabled“?
> 
> To be honest with you, I really don't know if it's linked, but after that my problem was resolved.
> 
> ```
> <ActionSheet id='feedbackActionSheet' ref={feedbackActionSheetRef} gestureEnabled>
> ...
> </ActionSheet>
> ```

So when you now open the actionsheet does it move up instantly?

**Comment by AlexAlexandre** [comment]
> > > > Same problem here, any solution ?
> > > > here some more info...
> > > > I fixed my problem adding `gestureEnabled` props
> > > 
> > > 
> > > How did this fix the delay problem and where did you added the „gestureenabled“?
> > 
> > 
> > To be honest with you, I really don't know if it's linked, but after that my problem was resolved.
> > ```
> > <ActionSheet id='feedbackActionSheet' ref={feedbackActionSheetRef} gestureEnabled>
> > ...
> > </ActionSheet>
> > ```
> 
> So when you now open the actionsheet does it move up instantly?

exactly, now the animation runs smoothly and instantly.
The problem that after closing the action sheet it is not possible to click on other buttons has also been fixed.
Everything works fine now.
