### ISSUE TITLE
does not allows to interact with buttons when keyboard is open

### ISSUE THREAD

**Issue by Amagnum** [ammarahm-ed/react-native-actions-sheet#244]
I have a button and an input text in the content of the action sheet. On inputting text, the keypad opens, but when clicking on the button (keyboard is open), the keypad goes down but doesn’t call onClick after that. You need to click on “Button” again to trigger onClick. 

v0.8.10

**Comment by parthkanani93** [comment]
+1

**Comment by bigeegib** [comment]
Did you solve this problem? If this problem is solved, please share.

**Comment by parthkanani93** [comment]
keyboardShouldPersistTaps={'handled'}

add this on your actionsheet props

<img width="555" alt="image" src="https://user-images.githubusercontent.com/47061736/234787401-9e681f02-48f6-4564-a705-2e9fa5b5fd68.png">

**Comment by Maheshoo7** [comment]
Adding `keyboardShouldPersistTaps="handled"` to ActionSheet Props worked for me.

**Comment by Nicoalz** [comment]
keyboardShouldPersistTaps property doesnt exist, still having the issue
