### ISSUE TITLE
Support Background Interaction

### ISSUE THREAD

**Issue by asp3** [ammarahm-ed/react-native-actions-sheet#25]
as the title says, i want to be able to have the action sheet show a little bit, but still have the buttons be clickable in the background. 
![0C961218-BCFC-4173-B171-4E8CBC28F63A](https://user-images.githubusercontent.com/11220954/82828722-b7359a00-9e7f-11ea-8a8c-1eda1df1187b.png)

**Comment by ammarahm-ed** [comment]
@aarongrider this feature is not supported yet. Will be implemented in the near future.

**Comment by rafaelsevla** [comment]
I also have this "problem"

**Comment by MrXyfir** [comment]
@ammarahm-ed Any update on timeline for this?

**Comment by ammarahm-ed** [comment]
@MrXyfir coming soon

**Comment by ahmad6242** [comment]
Any Update on this!

**Comment by MrXyfir** [comment]
Coming soon 😆

**Comment by ammarahm-ed** [comment]
@ahmad6242 @MrXyfir I was able to implement it partially on Android. Did not work on iOS. The only way I see of doing this is adding a native dependancy which can handle pointer events correctly.

**Comment by ahmedsayedabdelsalam** [comment]
anyone found a solution?

**Comment by mrkp** [comment]
Would love support for this solution

**Comment by jbagaresgaray** [comment]
Coming soon? When ? :D

**Comment by Insane34** [comment]
And soo, solution founded?)) Maybe anyone known how to solve this task with another packages?

**Comment by MrXyfir** [comment]
@Insane34 you should just build it custom. Make the bottom sheet an absolutely positioned view over the rest of your content. You'll need to wire up the gesture handler and do any animations yourself, but it's possible.

**Comment by ammarahm-ed** [comment]
It's possible obviously. Just not possible with the Current `ScrollView` implementation of the Sheet which does not work with `pointerEvents` properly but normal Views do. 

`ScrollView` is great because it is fully native and the Animations/Gestures are very performant compared to something implemented in JS using `Animated.View`. 

Another choice is to use Reanimated but this library was build to stay lean dependency free.

**Comment by ammarahm-ed** [comment]
Update: I have decided to ActionSheet. Background interaction support will be added in v0.8.0. 🚀

**Comment by ammarahm-ed** [comment]
Added. Will be released in v0.8.0 🚀
