### ISSUE TITLE
Payload props works only with onClose

### ISSUE THREAD

**Issue by AlexAlexandre** [ammarahm-ed/react-native-actions-sheet#251]
Hi there, 

I have an action sheet component, that needs to return a text input value. I'm doing that using the payload props. 
The problem is, the return only works if I pass the onClose props too.. 

Here's my code: 

Action sheet component: 

```
import React, { useRef, useState } from 'react';
import { Text, View } from 'react-native';
import ActionSheet, { ActionSheetRef, SheetProps } from 'react-native-actions-sheet';
import { textStyles } from '../../../theme';
import i18n from '../../../i18n';
import Input from '../../../components/Input';

export const actionSheetMoodThoughtsID = 'actionSheetMoodThoughtsID';

const MoodActionSheet = (props: SheetProps<{ title: string; thoughts: string }>) => {
  const moodActionSheetRef = useRef<ActionSheetRef>(null);
  const [thoughts, setThoughts] = useState(props.payload?.thoughts);
  return (
    <ActionSheet id={actionSheetMoodThoughtsID} ref={moodActionSheetRef} payload={thoughts}>
      <View>
        <Text style={[textStyles.title, textStyles.semiBold, textStyles.center]}>
          {i18n.t(props.payload?.title || '')}
        </Text>
        <Input
          autoFocus
          rounded
          value={thoughts}
          onChangeText={(value: string) => setThoughts(value)}
          returnKeyType='default'
          multiline
          numberOfLines={4}
        />
      </View>
    </ActionSheet>
  );
};

export default MoodActionSheet;

```

the function that open and receive the value: 

```
  const handleActionSheet = async () => {
    const response: string = await SheetManager.show(actionSheetMoodThoughtsID, {
      payload: { title: 'mood_what_thoughts_went_through_your_head', thoughts },
    });
    console.log('response: ', response);
    setThoughts(response);
  };
```

that way, the response always receives `undefined` but if I update the action sheet to  `    <ActionSheet id={actionSheetMoodThoughtsID} ref={moodActionSheetRef} payload={thoughts} onClose={() => {})> ` then everything works fine, 

Version of the library: 0.8.10. 
Problem happens on IOS, not tested on Android yet

**Comment by Kami1337** [comment]
Same issue here with latest version
` "react-native-actions-sheet": "^0.8.18",`

**Comment by ammarahm-ed** [comment]
@Kami1337 how are you hiding the sheet?

**Comment by Kami1337** [comment]
> @Kami1337 how are you hiding the sheet?

By tapping outside of sheet. I've just added a quick fix to render to check whether payload is defined

**Comment by nilox94** [comment]
In my case I'm getting an outdated result in any of the cases bellow:
```ts
const result = await SheetManager.show(payload);
/* `result` contains an outdated version of ActionSheet's payload */
```
```ts
SheetManager.show(
  payload,
  onClose((data) => {
    /* `data` contains an outdated version of ActionSheet's payload */
  },
)
```
Passing `onClose` as an inline arrow function will avoid caching the [hideSheet](https://github.com/ammarahm-ed/react-native-actions-sheet/blob/93cf9fc943cf9e30cbbb7d4b15a687d1f3fc040c/src/index.tsx#L420-L463) callback, which contains a reference to the payload.
The `useCallback` `dependencies` array might need to be updated to include the payload.
