### ISSUE TITLE
Broken on New Arch

### ISSUE THREAD

**Issue by cospin** [ammarahm-ed/react-native-actions-sheet#257]
Hey there, the sheet is not working correctly in a new project with `newArchEnabled=true`, and `RN 0.70.6`, this issue is present on iOS and Android.

When the sheet is rendered, it seems to be behind the background, making it impossible to interact with it or its elements. Pressing anywhere on the screen including the sheet simply causes it to close (as you are really pressing the background).

Testing with some options, activating `backgroundInteractionEnabled` does allow interaction with the ActionSheet. But this causes other problems, as that is not the correct way to use the ActionSheet (in a normal case).

Here a repo with the project: (new project with just this package and react-native-gesture-handler)
https://github.com/cospin/RNAS-NewArch

And here a video of the bug:

https://user-images.githubusercontent.com/2880114/211272688-6d171e56-c5e8-4d14-9238-65fa8525fd0c.mov

Here with `backgroundInteractionEnabled=true`:

https://user-images.githubusercontent.com/2880114/211272701-b658adfd-73eb-4f85-a918-9a16958a6cf5.mov

I already tried playing with react-native-gesture-handler, with or without it, the same result.

**Comment by cospin** [comment]
If I change the zIndez of the backdrop to zero, it works again: https://github.com/ammarahm-ed/react-native-actions-sheet/blob/8f44dd50ac02340b408c9c537fcb73eafde31857/src/index.tsx#L905

I tried adding or increasing other zIndex (trying to put the sheet on top of the overlay), but no success. The only thing that worked was to remove or set the zIndex of the backdrop to zero.

@ammarahm-ed is this patch safe or will I alter other things by setting that zIndex to zero?

**Comment by ammarahm-ed** [comment]
@cospin is this fix for zIndex only needed if background interaction is disabled?

**Comment by cospin** [comment]
Yes, only needed when background interaction is disabled, when is enabled I can touch the sheet without problems.

**Comment by ammarahm-ed** [comment]
I think you can create a PR with this.

**Comment by cospin** [comment]
Cloding this as you already fix this on https://github.com/ammarahm-ed/react-native-actions-sheet/commit/612c3af8ac473dba0b2bc85177f37922f7a4a1a3 

I stopped using New Arch because of the number of problems with other libraries.
