### ISSUE TITLE
action sheet cannot open? please help

### ISSUE THREAD

**Issue by kwameaj67** [ammarahm-ed/react-native-actions-sheet#26]
this is my code onPress={actionSheetRef.current.setModalVisible(true)}

**Comment by ammarahm-ed** [comment]
@kwameaj67 see the example.

```jsx
onPress={() => actionSheetRef.current?.setModalVisible()}
```

**Comment by kwameaj67** [comment]
> @kwameaj67 see the example.
> 
> ```js-jsx
> // first you need to create the ref.
> import {createRef} from "react";
> 
> const actionSheetRef = createRef();
> 
> // assign the ref to the ActionSheet
> <ActionSheet ref={actionSheetRef} ><ActionSheet/>
> 
> // and finally you can open it
> onPress={() => actionSheetRef.current?.setModalVisible(true)}
> ```

Thanks. Working as expected
