### ISSUE TITLE
can add  onBeforeClose method?

### ISSUE THREAD

**Issue by dppo** [ammarahm-ed/react-native-actions-sheet#262]
I want to hide the keyboard before touching the background to close the window

**Comment by jonxssc** [comment]
you could try to run `Keyboard.dismiss` inside the [onClose](https://rnas.vercel.app/reference/actionsheet#onclose) function and then close the actionsheet, but anyways the keyboard should automaticly dismiss when you close the actionsheet

**Comment by ammarahm-ed** [comment]
Good idea, I'll add it.

**Comment by ammarahm-ed** [comment]
Added in 0.8.19

**Comment by nolife08021** [comment]
onBeforeClose not calling in 0.8.21
