### ISSUE TITLE
Having height issue when i open keyboard

### ISSUE THREAD

**Issue by virenradadiya** [ammarahm-ed/react-native-actions-sheet#270]
Hi there,

I am facing an issue with the latest version of the library where the height of the action sheet changes after I open the keyboard and close the action sheet. I have attached a video demonstrating the issue.

Interestingly, this issue is not present in an older version of the library, which leads me to believe that it is a regression bug. I would greatly appreciate any assistance in resolving this issue.

Thank you in advance for your help!

**Comment by parthkanani93** [comment]
Same issue +1

**Comment by milankakadiya2001** [comment]
getting issues in my project  🥵 🥵 🥵

**Comment by tyetimoglu** [comment]
same issue +1

**Comment by Murad544** [comment]
same here

**Comment by Murad544** [comment]
just downgraded to version 0.7.2 and it works fine

**Comment by mohamed2m2018** [comment]
same issue

**Comment by YunySun** [comment]
same issue +1

**Comment by z1haze** [comment]
same issue... is this library maintained anymore? issue opened in february, lots of comments of users still facing the issue, and the author does not respond.

**Comment by parthkanani93** [comment]
Add this pram It will solve the issue

keyboardShouldPersistTaps={'handled'}
