### ISSUE TITLE
[feat request] Add ability to update payload of Action Sheet via SheetManager

### ISSUE THREAD

**Issue by Roka20012** [ammarahm-ed/react-native-actions-sheet#286]
Hello, @ammarahm-ed first of all thanks for the great package!

I didn't see any mentions of how I can update my payload data in case it's dynamic
The only way I ended up with it was to put my queries into ActionSheet and update data dynamically there

I am using SheetManager to manage my ActionSheet

Is there any way to do it or would it be a good feature for this package?

Let me know what you think, please.

**Comment by johnny-mcfadden-dailypay** [comment]
What are you trying to achieve? Are you trying to open an action sheet with different prop values? you should be able to just use the sheet manager show method to pass through a props payload and then access inside your action sheet component via props.payload.thePropName

**Comment by Roka20012** [comment]
> What are you trying to achieve? Are you trying to open an action sheet with different prop values? you should be able to just use the sheet manager show method to pass through a props payload and then access inside your action sheet component via props.payload.thePropName

@johnny-mcfadden-dailypay hello thanks for response)
Basically I want to open action sheet, and update value in that action sheet on a fly without closing and open it again with another data

Do you know how to achieve this behavior?

**Comment by johnny-mcfadden-dailypay** [comment]
Are you looking to:

1. open the action sheet with prop values?
2. whilst the action sheet is open and the user is looking at the action sheet, change the information displayed on the action sheet? Is this from a user interaction like a button click or an api call that runs when the action sheet opens?

**Comment by Roka20012** [comment]
Yes for example I open the action sheet and need to load some data from API, and update action sheet with this data

**Comment by Roka20012** [comment]
@johnny-mcfadden-dailypay 
>  Is this from a user interaction like a button click or an api call that runs when the action sheet opens?

Exactly this one

**Comment by johnny-mcfadden-dailypay** [comment]
Can you not just use normal react patters for this? When the api call finishes, update a local state hook inside the action sheet and use the state hook data as your presentational piece. IF you need to initially take in props to the action sheet you could just set this data as your initial state hook value, then override with an api call response.

**Comment by Roka20012** [comment]
@johnny-mcfadden-dailypay not sure it will work, but I will give it a try, thanks 👍

**Comment by AyoCodess** [comment]
> Can you not just use normal react patters for this? When the api call finishes, update a local state hook inside the action sheet and use the state hook data as your presentational piece. IF you need to initially take in props to the action sheet you could just set this data as your initial state hook value, then override with an api call response.

having to create separate state to mimic the state controlled outside the action sheet is a very difficult experience, the props.paylaod are not updated on the fly, we literally need to unmount the action sheet and remount it to see state updates.
