### ISSUE TITLE
flatlist warning

### ISSUE THREAD

**Issue by superandrew** [ammarahm-ed/react-native-actions-sheet#29]
Hello, as soon as I put a `<Flatlist />` on this component I get the `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead` warning.

Am I missing something? should I use something different for lists? Or is it normal and maybe it is just a matter of silencing the warning?

I plan to use this component as a drawer to make user choose from a filterable list.

**Comment by ammarahm-ed** [comment]
Lists inside the `ActionSheet` are not virtualized since it is using `ScrollView` for all the interacations. This is easily fixable but I have been a bit lazy lately to fix this issue. We just have to replace the `ScrollView` with a `Flatlist` and then use it for all the gesture handling.

**Comment by superandrew** [comment]
Ok, I'll take a look if I am able to change it and then I will make a PR. Are there tests to run?

**Comment by ammarahm-ed** [comment]
No, there aren't any tests. Basically what you need to do is, load everything as the first item in `Flatlist` or load it inside the `Flatlist` header when you replace the ScrollView. I think everything will work as expected after that.
