### ISSUE TITLE
Sending `onAnimatedValueUpdate` with no listeners registered.

### ISSUE THREAD

**Issue by LluisR** [ammarahm-ed/react-native-actions-sheet#290]
This warning has been launched when execute SheetManager.hide function. 
<img width="495" alt="Captura de Pantalla 2023-05-02 a las 14 05 28" src="https://user-images.githubusercontent.com/45036402/235661385-bb95e47e-99e2-4382-bf5c-666017a3239c.png">

Obviously, the "animated" prop of the ActionSheet object must be set to true. If there is no animation, the warning is not triggered. 

¿Any ideas?

Thank you!

**Comment by jonxssc** [comment]
Same problem, also no idea why that happens

**Comment by isilgawen** [comment]
Same issue here

**Comment by ayuleul** [comment]
i got the some logs.

**Comment by alex-pominov** [comment]
Same issue here

**Comment by sabuhiteymurov** [comment]
Is there any possible fix?

**Comment by EdsonJrx** [comment]
I've been used LogBox.ignoreLogs(['Sending `onAnimatedValueUpdate`']); for while.

**Comment by YuGer26** [comment]
Use actionSheetRef. current Show(); There wouldn't be this warning

**Comment by MaSMas0** [comment]
not sure but when i used onBeforeClose instead of OnClose and used actionSheetRef.current.show() & actionSheetRef.current.hide() the warning disappeared 

```js
      onBeforeClose={() => closeActionSheet()}
```
instead of 
```js
onClose ={()=>closeActionSheet()}
```

**Comment by recursivetree** [comment]
Can confirm I'm affected by this too
