### ISSUE TITLE
Doesn't work in screen presentation modal.

### ISSUE THREAD

**Issue by isilgawen** [ammarahm-ed/react-native-actions-sheet#293]
Hello, I try to use the SheetManager inside a Screen View with modal presentation. Like this :

```
<Stack.Group screenOptions={{ presentation: 'modal'}} >
          <Stack.Screen name="MyComponent" component={MyComponent} options={{ headerShown: false }} />
</Stack.Group>

```
In MyComponent, SheetManager.show doesn't work but no error.
With normal Screen without presentation: modal it works, but it's not what i want.

Any idea or workaround ?  thanks for your help.

**Comment by johnny-mcfadden-dailypay** [comment]
Same issue as https://github.com/ammarahm-ed/react-native-actions-sheet/issues/296 this issue can be closed and use linked one for discussion. 

But in short:
You need to register the sheets under a new context for a modal and add a sheet provider. https://rnas.vercel.app/reference/sheetprovider
