### ISSUE TITLE
Action sheet bottom space sometimes

### ISSUE THREAD

**Issue by MoRa2297** [ammarahm-ed/react-native-actions-sheet#299]
Sometimes when I open the Action sheet it gives me some space on the button and sometimes it doesn't give me. The yellow border in the video should stay ever at the bottom of the screen....

```typescript
<ActionSheet
      drawUnderStatusBar={true}
      ref={actionSheetRef}
      closable={true}
      backgroundInteractionEnabled={false}
      // useBottomSafeAreaPadding={isKeyboardOpen}
      useBottomSafeAreaPadding={true}
      closeOnTouchBackdrop
      // gestureEnabled
      isModal={false}
      defaultOverlayOpacity={0.2}
      containerStyle={{
        display: 'flex',
        // flexDirection: 'column',
        // backgroundColor: theme['color-primary-BK'],
        backgroundColor: 'red',
        borderTopLeftRadius: GLOBAL_BORDER_RADIUS,
        borderTopRightRadius: GLOBAL_BORDER_RADIUS,
        borderColor: 'yellow',
        borderWidth: 1,
        paddingBottom: 0,
      }}
      keyboardHandlerEnabled={true}>
      <CategoryForm category={{}} />
    </ActionSheet>
``` 

This is the code of how I have implemented it.

I tried also to remove the **CategoryForm** component but it isn't the cause of the issue. The problem is in the Action sheet.

Pls help me!

https://github.com/ammarahm-ed/react-native-actions-sheet/assets/17024202/473b14a7-2e0f-47aa-ad94-c091b730a8f1

**Comment by CallbackDan** [comment]
Hey @MoRa2297 did you find a fix for this ?

**Comment by GreedyWhale** [comment]
The same problem occurs whenever `isModal={false}` is set

**Comment by sabuhiteymurov** [comment]
Same problem happens

**Comment by jonxssc** [comment]
For anyone searching for a solution, removing the code i pointed at in [https://github.com/ammarahm-ed/react-native-actions-sheet/pull/328](https://github.com/ammarahm-ed/react-native-actions-sheet/issues/url) this request, should fix the weird spacing, tested it on version 0.8.29

**Comment by OwaisKorejo** [comment]
This worked for me:
`useBottomSafeAreaPadding={false}`

**Comment by boboxiaodd** [comment]
@ammarahm-ed 

I encountered a similar issue where sometimes extra blank space appears at the bottom of the sheet when it opens, and other times it's fine. I found a solution: add a state to control the visibility of the <View> inside the <ActionSheet>, and set it to visible after the onOpen event triggers. This causes the ActionSheet to recalculate its height, and the extra blank space no longer appears.

```tsx
const SomeSheet = () => {
	const [showSheet, setShowSheet] = useState(false);
	const onOpen = () => {
		setShowSheet(true);
	};
    return (
        <ActionSheet useBottomSafeAreaPadding onOpen={onOpen}>
		<View style={{display: showSheet ? "flex":"none"}} >
			<View style={{height:50}}></View>
		</View>
        </ActionSheet>
    )
}
export default SomeSheet;
