### ISSUE TITLE
useRouter is being returned as undefined function

### ISSUE THREAD

**Issue by dwrynngs** [ammarahm-ed/react-native-actions-sheet#303]
When I follow the example for using routes, I get an error on the following line

const router = useRouter();

error says "undefined is not a function".

I import it as follows:

import ActionSheet, { useSheetRouteParams, useScrollHandlers, useRouter } from 'react-native-actions-sheet';

I honestly don't know what I am doing wrong.  The only difference is I am writing in javascript, not in typescript.

**Comment by luckyxhu** [comment]
use `useSheetRouter` instead.
