### ISSUE TITLE
@shopify/flash-list not found

### ISSUE THREAD

**Issue by NoodleOfDeath** [ammarahm-ed/react-native-actions-sheet#304]
minor bug fixed by installing the dependency, but should be listed as one

**Comment by jenssogaard** [comment]
I would not call a missing dependency a minor bug :)

**Comment by thenriquedb** [comment]
This error happens only in version 0.9 alpha. I installed 0.8.29 and it worked correctly

**Comment by js-pk** [comment]
@ maintainers :) .. The new alpha releases are tagged as latest in npm. You should probbaly tag them as `beta` and set 0.8.29 as `latest`
<img width="904" alt="스크린샷 2023-08-26 오후 3 09 32" src="https://github.com/ammarahm-ed/react-native-actions-sheet/assets/42714574/cfe6f2e9-245b-4951-ab09-9b732ae6d2be">

https://docs.npmjs.com/cli/v9/commands/npm-dist-tag

**Comment by yakshao** [comment]
I am getting this error right now on the latest version (0.9.6).
