### ISSUE TITLE
When data is received from a service, ActionSheet becomes not visible.

### ISSUE THREAD

**Issue by superandrew** [ammarahm-ed/react-native-actions-sheet#31]
Probably there is an automatic toggle of the ModalVisible state. Is this by design?

If so I guess I could keep track of the modalVisible state outside the component? Or is there a way to disable the modalVisible automation?

Example gif:

Working with static data (provided from outside):
![CleanShot 2020-06-11 at 09 45 54](https://user-images.githubusercontent.com/71364/84359156-84eaa300-abc8-11ea-9c3b-5905215b9f4e.gif)

Dynamic data:
![CleanShot 2020-06-11 at 09 46 30](https://user-images.githubusercontent.com/71364/84359162-86b46680-abc8-11ea-9058-1ddaf352dd12.gif)

**Comment by ammarahm-ed** [comment]
i don't understand, why is the `ActionSheet` hiding after you type and submit info? I use `ActionSheet` with dynamic data and it works just fine. The modal does not hide Automatically unless you call `setModalVisible` or press outside your component on the backdrop etc.

**Comment by superandrew** [comment]
Ok weird, then I must have been some mistake. Well that is good news. Since I am embedding ActionSheet inside a `<Dropdown />` component, that might be related with re-rendering the component and reinstantiating `<ActionSheet />`? it should not, however.

This is my Dropdown component, which can receive an array of options, or a dataProvider method.

```
import React, { createRef, useState, useCallback, useEffect } from "react";
import ActionSheet from "react-native-actions-sheet";
import {
  View,
  Text,
  TouchableOpacity,
  FlatList,
  ListRenderItem,
  TextInput,
  Modal,
} from "react-native";
import {
  IComboboxItemDto,
  IGetComboboxItemsInput,
} from "irideweb2-data-access";
import { AxiosRequestConfig } from "axios";

export interface IDataProviderParams
  extends Pick<IGetComboboxItemsInput, "parentId" | "limit"> {}
interface Props {
  dataProvider?: (
    params?: IGetComboboxItemsInput,
    options?: AxiosRequestConfig
  ) => Promise<IComboboxItemDto[]>;
  dataproviderParams?: IDataProviderParams;
  options?: IComboboxItemDto[];
  onSelect?: (value: IComboboxItemDto) => void;
}

export const Dropdown = (props: Props) => {
  const actionSheetRef = createRef<ActionSheet>();
  const [options, setOptions] = useState<IComboboxItemDto[]>();

  const [searchText, setSearchText] = useState<string>();
  const [selectedItem, setSelectedItem] = useState<IComboboxItemDto>();

  const onChangeText = (text: string) => {
    setSearchText(text);
    if (props.dataProvider != null) {
      props
        .dataProvider({ searchTerm: text })
        .then((items: IComboboxItemDto[]) => {
          setOptions(items);
        });
    }
  };

  useEffect(() => {
    if (!!props.options) {
      setOptions(props.options);
    }
  }, [props.options]);

  const onItemSelect = React.useCallback((item: IComboboxItemDto) => {
    if (props.onSelect) {
      setSelectedItem(item);
      actionSheetRef.current?.setModalVisible(false);

      return props.onSelect(item);
    }
  }, []);

  const renderItem: ListRenderItem<IComboboxItemDto> = ({ item }) => {
    console.log("elements received" + options);
    return (
      <View>
        <TouchableOpacity onPress={() => onItemSelect(item)}>
          <Text key={item.value}>{item.displayText}</Text>
        </TouchableOpacity>
      </View>
    );
  };
  let actionSheet;
  return (
    <View>
      <TouchableOpacity
        onPress={() => {
          actionSheetRef.current?.setModalVisible(true);
        }}
      >
        <Text>{selectedItem?.displayText ?? "Scegli"}</Text>
      </TouchableOpacity>
      <ActionSheet closable={false} ref={actionSheetRef}>
        <View
          style={{
            flex: 1,
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            marginTop: 50,
            marginBottom: 50,
          }}
        >
          <TextInput
            placeholder={"cerca"}
            value={searchText}
            onChangeText={onChangeText}
          ></TextInput>
          <FlatList
            keyExtractor={(item: IComboboxItemDto) => item?.value as string}
            data={options}
            renderItem={renderItem}
          ></FlatList>
        </View>
      </ActionSheet>
    </View>
  );
};
```

**Comment by superandrew** [comment]
I manually set modalVisible(true) and modalVisible(false) manually so I wasn't expecting it to change visibility state of modal.

**Comment by superandrew** [comment]
Ok, I noticed that the problem arises when I `setOptions` with the result of the fetch. By commenting it I get no new results but the modal stays open. Probably the problem is there, I'll look into it.

**Comment by ammarahm-ed** [comment]
I think this is happening because the underlying dropdown component is rerendered. You can fix this simply but placing the `ActionSheet` globally outside your dropdown components. Then you can simply close and open the `ActionSheet` using an Event and pass the data in the event which is used to show the information. This way, your ActionSheet will never be rerendered once the App is created. It will only show whenever there is new data available and you open it.

**Comment by superandrew** [comment]
I will try. Have you got any example on how to pass data through an event? I'm not sure I understood. Thank you for helping, though

**Comment by ammarahm-ed** [comment]
Its pretty simple, place the ActionSheet alongside your flatlist then from each rendered component, call the ActionSheet opening function. Put the data you want to pass in the state, update the state, then open the ActionSheet. The ActionSheet will take the data as a prop and use it inside the component you have created.

**Comment by superandrew** [comment]
ok, so I have a Screen in which I put the ActionSheet alongside a flatlist, the data in the state. Then I forward the ref from the screen to the Dropdown component, right? I will give it a try. Thanks! Btw maybe a modalVisible prop for Actionsheet could help it be managed from outside?

**Comment by ammarahm-ed** [comment]
Even if you have the current information, still you cannot handle the issue you are facing.

**Comment by ammarahm-ed** [comment]
this issue is stale and appears to be fixed for you. closing. reopen if needed.
