### ISSUE TITLE
Latest version throws "@shopify/flash-list" error.

### ISSUE THREAD

**Issue by sadewole** [ammarahm-ed/react-native-actions-sheet#312]
Installing the latest version throws a build error.  Apparently "@shopify/flash-list" was used in one of the files but couldn't be resolved.

iOS Bundling failed 434ms
Unable to resolve "@shopify/flash-list" from "node_modules/react-native-actions-sheet/dist/src/views/FlashList.js"

**Comment by Medkhat** [comment]
Hi all! I also had this problem and installed this package and then was another issue that should have been installed `react-native-gesture-handler` package. So, I installed this package too then it worked. Maybe try!

1) Install `@shopify/flash-lisrt`;
2) Install `react-native-gesture-handler`;

**Comment by Dror-Bar** [comment]
This would be useful to mention in the [installation](https://rnas.vercel.app/installation) documentation

**Comment by z1haze** [comment]
yeah, first time checking out this library, and I read `...and zero dependency code for react native.` in the introduction. not a great start to my experience.

**Comment by Medkhat** [comment]
Yeah, but when you will start this package, it's really cool.
I have tried use the `@gorhom/bottom-sheet`, but this package requires the `react-native-reanimated`. So, when I installed and configured,  my application crashes on each reboot cause of `react-native-reanimated`...

**Comment by yvbeek** [comment]
Is the `@shopify/flash-list` really necessary though? It is normally used in scenarios where performance is really key, where the user can scroll through a long list. Wouldn't that be a bit overkill for a small actionsheet? It really adds to the (indirect) dependencies.
