### ISSUE TITLE
Strange actions sheet behaviour on Android

### ISSUE THREAD

**Issue by Medkhat** [ammarahm-ed/react-native-actions-sheet#321]
### Examples here:

https://github.com/ammarahm-ed/react-native-actions-sheet/assets/42961493/e8529990-8775-4e44-aec7-12bd17bc50e9

https://github.com/ammarahm-ed/react-native-actions-sheet/assets/42961493/2ac8082c-78f0-4fe4-9c40-3ac7fe88c648

**Comment by Medkhat** [comment]
Hello again! Does anyone know the answer to this?

**Comment by Medkhat** [comment]
@mauricedoepke No I don't use scrollview/flatlist.
I'll double check again.

**Comment by Medkhat** [comment]
@mauricedoepke Have you tested your code on both OS? So, can you provide your configs?

**Comment by ammarahm-ed** [comment]
Hi, provide a reproducible example of the issue on Android.

**Comment by Medkhat** [comment]
I created Expo Snack but here all is fine. 
However, I'm working with React Native CLI in my machine. I will check again when I'll build for Android. If it doesn't work out then I will come back.
@mauricedoepke  @ammarahm-ed  Thank you so much!

**Comment by oleksii-lyhun** [comment]
Running with the same issue. It's reproducing randomly. On some devices, everything works well on some ActionSheet showing, and when pressing some buttons inside ActionSheet it's going to be not visible but not hidden

**Comment by Kavosh-m** [comment]
same. any workaround yet?

**Comment by JaifDev** [comment]
Any fixes for this? I am facing the same issue on newArch

**Comment by Medkhat** [comment]
@JaifDev @Kavosh-m 
I don't know how it was fixed. I finished the iOS version of my app, and after this, I ran it on Android. Currently, everything is fine. So, please check your imports or other configurations. After registering the sheets, you need to import the relevant file into App.tsx. Also, make sure to check the import of react-native-gesture-handler in the index.js file.

index.js:
```
...
import 'react-native-gesture-handler';
...
```

actions-sheet-manager.ts:
```
import {registerSheet} from 'react-native-actions-sheet';
registerSheet('YourExampleSheet', YourExampleSheet);
```

App.tsx:
```
...
import '@/actions-sheet-manager';
...
```
