### ISSUE TITLE
How to limit max expanded height?

### ISSUE THREAD

**Issue by z1haze** [ammarahm-ed/react-native-actions-sheet#322]
How do you prevent a sheet from going beyond a max height or snap point? I have tried setting a snap point to 75 for example, but it will allow me to expand it even further, if there is content in the view large enough. The preference would be to set a limit for the max height and have the scroll view handle the overflow.

Here is an example of difference in functionality between platforms. We do not like the ios behavior of how it will up into the status bar. it should behave like android does
<img width="1264" alt="image" src="https://github.com/ammarahm-ed/react-native-actions-sheet/assets/6024725/90c4c692-4e37-4ed5-94f4-a15df49a5267">

**Comment by YeeWan0217** [comment]
have same problem too

**Comment by justinmwarner** [comment]
Not sure if you tried, but passing in `snapPoints={[80]}` sets the height to 80%. This works on my end at least.

**Comment by YeeWan0217** [comment]
@justinmwarner Thank you for the solution, my solution is set the style of ScrollView in ActionSheet with `maxHeight: Platform.OS == 'ios' ? Dimensions.get('window').height * 0.3 : Dimensions.get('window').height * 0.4,`. But I do like your solution.

**Comment by eisodev** [comment]
https://rnas.vercel.app/guides/safearea

Isn't the drawUnderStatusbar={false} supposed to solve this problem? That prop does nothing for me it seems.

Version 0.8.21

**Comment by ammarahm-ed** [comment]
This will be fixed in #330 

You can set the `maxHeight` on containerStyle prop btw for now.

**Comment by z1haze** [comment]
> Not sure if you tried, but passing in `snapPoints={[80]}` sets the height to 80%. This works on my end at least.

Read the op issue. It mentions using snap points and it does not fix the issue. Your test case I imagine does not have enough content in it to see the actual issue...

**Comment by ammarahm-ed** [comment]
> > Not sure if you tried, but passing in `snapPoints={[80]}` sets the height to 80%. This works on my end at least.
> 
> Read the op issue. It mentions using snap points and it does not fix the issue. Your test case I imagine does not have enough content in it to see the actual issue...

You can't limit max height with snap points, you can however using maxHeight on `containerStyle` to do it.  Snap points are used to snap to a certain section of sheet, the sheet will always open to 100% of its actual height based on the content.

**Comment by blazk0** [comment]
Using `maxHeight` to `containerStyle` doesn't work on version `0.9.3`

**Comment by leymytel** [comment]
@blazk0 did you find any solutions or workarounds for this issue?
