### ISSUE TITLE
Bottomsheet goes out of the screen in landscape mode

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [ammarahm-ed/react-native-actions-sheet#324]
Bottomsheet works perfectly in portrait mode but when we change orientation bottomsheet goes out of the screen

Here is example video

https://github.com/ammarahm-ed/react-native-actions-sheet/assets/25653690/c760a4df-86af-48cc-bb93-50e3227557f3

**Comment by ammarahm-ed** [comment]
Fixed in v0.9.2
