### ISSUE TITLE
Android does not overlap the navigation bar

### ISSUE THREAD

**Issue by sbalcin** [ammarahm-ed/react-native-actions-sheet#325]
Hi,
is there any way to remove navigation bar on bottom sheet on Android or changing color of it, where is the theme coming from, how can i override it? By the way it's already overlapping on IOS.

<img width="440" alt="Screenshot 2023-12-13 at 11 11 34" src="https://github.com/ammarahm-ed/react-native-actions-sheet/assets/6813922/f994a597-57f1-4b00-b698-bfda8f43296f">

**Comment by jonxssc** [comment]
+1 i would also like to know that, i have only found how to change the color of the navigationbar but not how to make it transparent, i tried this using react-native-navigation but somehow the Actionsheet overrides it to a color
`<Stack.Navigator screenOptions={{navigationBarColor:'transparent'}}> `

**Comment by IhorReactNative** [comment]
I had same issue too:

![Screenshot 2024-01-01 at 20 54 32](https://github.com/ammarahm-ed/react-native-actions-sheet/assets/69585418/44276ad1-3b8d-40ec-bc9e-51fc4bd0e647)

Fixed via patch-package
```
diff --git a/node_modules/react-native-actions-sheet/dist/src/styles.js b/node_modules/react-native-actions-sheet/dist/src/styles.js
index 41d60b0..685271f 100644
--- a/node_modules/react-native-actions-sheet/dist/src/styles.js
+++ b/node_modules/react-native-actions-sheet/dist/src/styles.js
@@ -19,8 +19,7 @@ export var styles = StyleSheet.create({
         alignSelf: "center"
     },
     parentContainer: {
-        width: "100%",
-        height: "100%",
+        flex: 1,
         justifyContent: "center",
         alignItems: "center"
     }

```

Result:
![Screenshot 2024-01-01 at 20 58 46](https://github.com/ammarahm-ed/react-native-actions-sheet/assets/69585418/1e61babd-a5d8-4ff2-9e74-1bcc9ff41b39)

**Comment by jonxssc** [comment]
Different approche is to just set isModal={false}, thats how i "fixed" it.

**Comment by ammarahm-ed** [comment]
I will add this to docs later but you can fix that on android using this, on iOS it's already correct I think.
https://stackoverflow.com/questions/74256638/react-native-modal-bypasses-expo-navigation-bar-setting
