### ISSUE TITLE
Sheet Manager does not work in react-native version 0.73.1

### ISSUE THREAD

**Issue by omerkok** [ammarahm-ed/react-native-actions-sheet#326]
SheetManager is not working in react-antive 0.73.1 version. These action sheets cannot be managed with the provider. When SheetManager.show('sheetname') is run, no response is received. Since this feature does not work, sheets can be intervened with ref.

How can the Sheetmanager issue be resolved?

The issue is present in all 3 versions: 0.8.10, 0.8.29 and 0.9.0-alpha.24.

**Comment by umairb-pedal** [comment]
This seems to be a problem with hermes and it's relentless optimisation. I have managed to "fix" it by having the code for the component and the `registerSheet` call in the same place. That way, hermes is not forced to throw the component away as it will think the component is being used.

**Comment by umairb-pedal** [comment]
Ok after a little bit more of an investigation, I can confirm this works:

```
registerSheet("sheet), function Sheet() {
    return (
        <View>
            <Text>Hello</Text>
        </View>
    );
});
```

So components need to be inlined. 

It seems like either metro/babel or hermes is aggressively removing components that are not directly a part of the component hierarchy. I'm not sure what the library author can do about this other than a huge refactor, and I'm also not sure if there are some compiler hints to not remove components (if they are being removed at compile stage).

But in any case, there is a workaround.

**Comment by Mangoz1x** [comment]
> SheetManager is not working in react-antive 0.73.1 version. These action sheets cannot be managed with the provider. When SheetManager.show('sheetname') is run, no response is received. Since this feature does not work, sheets can be intervened with ref.
> 
> How can the Sheetmanager issue be resolved?
> 
> The issue is present in all 3 versions: 0.8.10, 0.8.29 and 0.9.0-alpha.24.

I managed to fix it by navigating to ```node_modules\react-native-actions-sheet\dist\src\views\FlashList.d.ts``` directory, and removing ```| undefined``` from line 5

This is what the new FlashList.d.ts file should look like.
```
import { FlashList as SPFlashList, MasonryFlashListProps } from '@shopify/flash-list';
import React from 'react';
export declare const FlashList: typeof SPFlashList;
export declare const MasonaryFlashList: <T>(props: MasonryFlashListProps<T> & {
    ref?: React.RefObject<import("@shopify/flash-list").MasonryFlashListRef<T>>;
}) => React.ReactElement<any, string | React.JSXElementConstructor<any>>;
//# sourceMappingURL=FlashList.d.ts.map
```

**Comment by omerkok** [comment]
<img width="459" alt="Ekran Resmi 2024-01-11 22 40 10" src="https://github.com/ammarahm-ed/react-native-actions-sheet/assets/48768206/abed9eed-5fc5-4154-a620-170c091a3459">

I am already creating registerSheet and I am sure that it is correct. SheetManager does not give any reaction or error even though everything is correct in version 0.73.1. That's why I couldn't fully understand what you said. I mentioned the unresponsiveness of the SheetManager.show function.

**Comment by omerkok** [comment]
<img width="308" alt="Ekran Resmi 2024-01-11 22 44 32" src="https://github.com/ammarahm-ed/react-native-actions-sheet/assets/48768206/29af83cb-4c50-4dab-9d98-c6d00ad7f8eb">

The error given when I do not have this library installed in my @shopify/flash-list project is different. Unfortunately, I can't get any errors. There is just a lack of reaction.
