### ISSUE TITLE
Wrong device height calculation on Android devices

### ISSUE THREAD

**Issue by hsnaydd** [ammarahm-ed/react-native-actions-sheet#33]
Hi, the height calculation does not work correctly on Android devices. According to my research, we should subtract the status bar height from the window height. Because as far as I can observe, the modal starts under the status bar on Android. 

<img src="https://user-images.githubusercontent.com/2880893/87312637-7ece4600-c529-11ea-9896-2ea796a90837.png" width="375" />

**Comment by ammarahm-ed** [comment]
You mean to say the bottom navbar? Have you tried adding a Footer?

**Comment by hsnaydd** [comment]
No, It is not related to the footer. You will understand what exactly I mean with the following image;

![Group 1](https://user-images.githubusercontent.com/2880893/87393498-f26a6480-c5b6-11ea-8576-e9ed66e6e5b8.png)

On Android Modal starts under the status bar but you set the modal height to device height, so part of the modal is off the screen.
