### ISSUE TITLE
[0.9.1] closing sheet with keyboard open, resizing screens

### ISSUE THREAD

**Issue by Engazan** [ammarahm-ed/react-native-actions-sheet#335]
react-native-actions-sheet: 0.9.1
react-native: 0.72.6

**problem**
- when keyboard is open in opened sheet, and i click onbackdrop to close it, next time i reopen this sheet it will be like keyboard was already open but its not

video: 

https://github.com/ammarahm-ed/react-native-actions-sheet/assets/53254371/1e17a1a8-b56e-4aeb-8420-5d65b0b0e6d2

**Comment by ammarahm-ed** [comment]
Fixed in v0.9.2
