### ISSUE TITLE
bounces={true} does not work on ScrollView

### ISSUE THREAD

**Issue by richardshaw700** [ammarahm-ed/react-native-actions-sheet#369]
This should be default behaviour on iOS for scroll views, but it does not work, nor does it work when setting explicitly bounces={true}. 

The regular react-native ScrollView sort of works -- it doesn't pick up the intention to dismiss the sheet with a swipe sheet unless the bounce has completely stopped moving.

**Comment by ammarahm-ed** [comment]
This is disabled and no plans to support it since it conflicts with action sheet gestures
