### ISSUE TITLE
Sheet temporarily completely closes when scrollview content size decreases

### ISSUE THREAD

**Issue by mclrc** [ammarahm-ed/react-native-actions-sheet#399]
Hello! First of all, thank you for your work on this library!

I have a small problem. I'm using an actionsheet for a form that changes in height quite dramatically when you select options, as the option list then collapses (or expands when deselecting). For expansion, everything works perfectly, but it seems that when collapsing such an options list, the sheet height does not go down to fit the content height/a snap point, but instead collapses completely for a split second and then opens again. While this doesn't affect usability, it does look a little akward. Is there anything I should keep in mind with such size adjustments to prevent this, or can I tweak the animations a little? I've tried messing with the animation config to minimize spring bounce but nothing seems to work.
Is it perhaps possible to disable automatic size adjustments entirely so i can work around this by snapping to snap points explicitly?

Help would be really appreciated! Cheers!

![Simulator Screen Recording - iPhone 16 Pro - 2024-11-25 at 12 49 44](https://github.com/user-attachments/assets/ccaf8cf7-16e1-4a1e-a5da-291085efed44)

**Comment by mclrc** [comment]
Nevermind, providing more snap points and snapping to them solved this problem

**Comment by r-obeen** [comment]
I have this exact issue... Anybody knows why this happens ? It occurs when content's height reduces, not the opposite strangely...
