### ISSUE TITLE
ReferenceError: Keyboard is not defined

### ISSUE THREAD

**Issue by dmantelli** [ammarahm-ed/react-native-actions-sheet#40]
With the simple example, when I try to open the screen an error occurred:

ReferenceError: Keyboard is not defined in ActionSheet.

Additional information:
React-native: 0.62.2
React: 16.11.0
OS: latest MacOS X & latest iOS 13

```
import React, { Component, createRef } from 'react';
import ActionSheet from "react-native-actions-sheet";
```

```
render(){

const actionSheetRef = createRef();

...


<ActionSheet ref={actionSheetRef}>
<View>
       <Text>YOUR CUSTOM COMPONENT INSIDE THE ACTIONSHEET</Text>
 </View>
 </ActionSheet>


}
```

**Comment by ammarahm-ed** [comment]
Hey! thanks for reporting, I will fix this in a few minutes and publish a new version

**Comment by ammarahm-ed** [comment]
I just published a new version that fixes this!. **v0.3.3**
