### ISSUE TITLE
Child input element with autofocus

### ISSUE THREAD

**Issue by mortocks** [ammarahm-ed/react-native-actions-sheet#42]
Great library but am having trouble having the sheet appear with the keyboard already focused on a child element. using 

```
<Input autofocus {....} />
```

the sheet jumps up and down on and off the screen forever. 

If there is another api implementation to achieve the sheet appear with the keyboard and an input selected I'd be super grateful.

**Comment by ammarahm-ed** [comment]
There isn't, focus the input after the ActionSheet is displayed.

**Comment by thisispranavvasudev** [comment]
Still this issue is existing..
"react-native-actions-sheet": "0.6.1",
