### ISSUE TITLE
Sheet slides down when input text

### ISSUE THREAD

**Issue by Maclay74** [ammarahm-ed/react-native-actions-sheet#44]
Hi, thanks for such amazing library.

I experience problem with input field inside sheet on Android.

When I focus on input field, sheet changes its size accordingly, but when I start typing something, it slides down.
However, when I open it again, it works as intended. 

And probably it's related to the parent, which has flexGrow: 1. When I disable it, problem disappear. 

Do you have any suggestions how to avoid it without disabling flexGrow?

Thanks!

**Comment by mortocks** [comment]
+1 but for me this behaviour only appears to happen on Android, iOS works just fine

**Comment by ammarahm-ed** [comment]
Hey there, I will try to debug this, can you leave a simple example code of how you are using flexGrow? @mortocks
