### ISSUE TITLE
Closed automaticaly when using graphql + flatlist

### ISSUE THREAD

**Issue by catnuxer** [ammarahm-ed/react-native-actions-sheet#46]
Hi @ammarahm-ed  do you able using flatlist in rerender data ?, I have try using flatlist it's closed automaticaly only when data using query graphql. but it works well when data static.

**Comment by ammarahm-ed** [comment]
Its because your component is rerendered and the ActionSheet is in the same component. Move it out, place it on a higher level component and show/hide with events.
