### ISSUE TITLE
Keyboard avoiding transformY seems to increase when multiple input fields are stacked

### ISSUE THREAD

**Issue by te-online** [ammarahm-ed/react-native-actions-sheet#57]
When I stack multiple input fields, wrapped by `Views`, it seems that the "gap" at the bottom increases to an evermore excessive amount to compensate for the keyboard. With one input field it works just fine, but with three I observe some weird effects. 

Tested with version `0.4.2`
react-native `0.63.2`
expo `39.0.5`

I've been getting as close to the [example](https://github.com/ammarahm-ed/react-native-actions-sheet/blob/master/example/App.js) as I can. Using a `ScrollView` and hooking up all the events. The wrapping component is a bit more complex, that's why I'm not posting the full code here.

Looking into the source, I think that this is the place where it goes wrong:
https://github.com/ammarahm-ed/react-native-actions-sheet/blob/master/src/index.js#L425

If I simply say `const gap = -1 * fieldHeight;` it works for my use-case.

Any ideas on why the initial calculation is breaking here? 😅

**Comment by ammarahm-ed** [comment]
Hey there, the keyboard handling code is changed on the develop branch. Can
you test it and see if it is working as expected. Ignore the flicker since
i have to fix it.

**Comment by te-online** [comment]
Hey @ammarahm-ed, thanks for your quick reply – I tried the code in `develop`, but it didn't change much. Only that the distance is growing by a bit smaller amount and that the sheet's overflow to the bottom is now hidden. 😕

**Comment by te-online** [comment]
I experimented a little with the example. Adding more input fields and wrapping them in `Views`. Also applying some of the styling I'm using in my own component. But I couldn't quite reproduce the issue, although it seems somewhat unreliable where each input happens to “land” after focusing it.

**Comment by dgsunesen** [comment]
It doesn't seem to be an issue running Android 11. I see that there is a design change on the keyboard between v10 and v11 of Android, but dimensions seems to be the same though.
