### ISSUE TITLE
Feature request - drag-up to bounce.

### ISSUE THREAD

**Issue by IceDev-xyz** [ammarahm-ed/react-native-actions-sheet#58]
When the sheet is visible, the user can close it by drag it down, dragging up _should_ also have an effect: bounce back to its size.

It just looks cool :)

https://user-images.githubusercontent.com/54909232/107163278-5c40c600-696e-11eb-82f7-ae598df003d0.mp4

**Comment by ammarahm-ed** [comment]
@IceDev-xyz Cool effect! I will look into implementing it.

**Comment by ammarahm-ed** [comment]
The effect can be produced using the current implementation. Just set `initialOffsetFromBottom` to `0.95`or `0.90`.
