### ISSUE TITLE
Methods Missing from Type Definitions

### ISSUE THREAD

**Issue by SaltedBlowfish** [ammarahm-ed/react-native-actions-sheet#59]
`addHasReachedTopListener` and `removeHasReachedTopListener` are missing from the TypeScript definitions causing an error when importing from `react-native-actions-sheet`.

Reproduction:

1. Start TypeScript React Native project
2. Import the required functions:
```
import ActionSheet, {
  addHasReachedTopListener,
  removeHasReachedTopListener,
} from 'react-native-actions-sheet';
```

Output: 
```
Module '"react-native-actions-sheet"' has no exported member 'addHasReachedTopListener'. Did you mean to use 'import addHasReachedTopListener from "react-native-actions-sheet"' instead?
Module '"react-native-actions-sheet"' has no exported member 'removeHasReachedTopListener'. Did you mean to use 'import removeHasReachedTopListener from "react-native-actions-sheet"' instead?
```

**Comment by ammarahm-ed** [comment]
I will add the defs! Thanks for reporting

**Comment by naderalfakesh** [comment]
Currently I am using until we get the defs in the new release:
Thanks in advanced 
```
useEffect(() => {
    DeviceEventEmitter.addListener('hasReachedTop', callback);
    return () => {
      DeviceEventEmitter.removeListener('hasReachedTop', callback);
    };
  }, []);
```

**Comment by ammarahm-ed** [comment]
fixed on master

**Comment by efstathiosntonas** [comment]
@ammarahm-ed why `onPositionChanged` is a mandatory prop? I think it should be optional

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed why `onPositionChanged` is a mandatory prop? I think it should be optional

Yeah, I think I forgot to add "?" in type defs

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed why `onPositionChanged` is a mandatory prop? I think it should be optional

Yeah, I think I forgot to add "?" in type defs

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed why `onPositionChanged` is a mandatory prop? I think it should be optional

Published new version with the fix.

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed why `onPositionChanged` is a mandatory prop? I think it should be optional

Published new version with the fix.

**Comment by efstathiosntonas** [comment]
Thanks for the quick fix!! Keep up the great work!
