### ISSUE TITLE
Always keep full sheet above the keyboard

### ISSUE THREAD

**Issue by JordanSalinas** [ammarahm-ed/react-native-actions-sheet#60]
Is there a way to keep the entire sheet above the keyboard? Currently when the user focuses an input the keyboard will pop up and cover whatever portion of the sheet is below the input that is focused.

**Comment by arakovskis** [comment]
You can increase your input height to action sheet height and wrap actionSheet into keyboardavoidingview.

**Comment by ctwillie** [comment]
@ammarahm-ed What is the best way to solve this? What @arakovskis suggested?

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed What is the best way to solve this? What @arakovskis suggested?

Use master branch and use `keyboardMode` prop. Set it to `position`.

**Comment by ctwillie** [comment]
@ammarahm-ed Thanks for the reply! Do you have plans for tagging these new changes so we don't have to require by branch name.

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed Thanks for the reply! Do you have plans for tagging these new changes so we don't have to require by branch name.

Hopefully soon. Maybe this week.

**Comment by ahmad6242** [comment]
"keyboardMode" its doing nothing for me always the same.

![Screenshot_1627824736](https://user-images.githubusercontent.com/12858657/127772752-297db61e-6009-4d56-b5a9-b9fde075c24b.png)

![Screenshot_1627824666](https://user-images.githubusercontent.com/12858657/127772741-bb74acbb-a953-4315-82e5-2207cd9afb7b.png)

**Comment by ctwillie** [comment]
Are you pulling in the master branch as he stated above. It worked for me when I did. The entry in your package.json file should look like this.

"react-native-actions-sheet": "https://github.com/ammarahm-ed/react-native-actions-sheet"

These changes may be tagged now, not sure.

**Comment by ammarahm-ed** [comment]
> "keyboardMode" its doing nothing for me always the same.
> 
> ![Screenshot_1627824736](https://user-images.githubusercontent.com/12858657/127772752-297db61e-6009-4d56-b5a9-b9fde075c24b.png)
> 
> ![Screenshot_1627824666](https://user-images.githubusercontent.com/12858657/127772741-bb74acbb-a953-4315-82e5-2207cd9afb7b.png)
> 

The keyboardMode prop has been removed. The actionsheet by default shows above the keyboard now. 

But the version isn't tagged so just use master branch for now

**Comment by ahmad6242** [comment]
I did run the following command the use the master branch 
yarn add react-native-actions-sheet#master
is that the right way ?
@ammarahm-ed 
@ctwillie

**Comment by ammarahm-ed** [comment]
> I did run the following command the use the master branch 
> yarn add react-native-actions-sheet#master
> is that the right way ?
> @ammarahm-ed 
> @ctwillie 

The new version is released. Install from npm. ` npm install react-native-actions-sheet@latest`

**Comment by ahmad6242** [comment]
Thanx i will try it.

**Comment by ahmad6242** [comment]
I installed The new version, Install from npm. npm install react-native-actions-sheet@latest


Its throwing error! Please check. 

![image](https://user-images.githubusercontent.com/12858657/127977561-81fba3bd-dd10-4d98-9eb1-62fd1f5d8af6.png)

**Comment by Hridey27** [comment]
> I installed The new version, Install from npm. npm install react-native-actions-sheet@latest
> @ammarahm-ed
> 
> Its throwing error! Please check.
> 
> ![image](https://user-images.githubusercontent.com/12858657/127977561-81fba3bd-dd10-4d98-9eb1-62fd1f5d8af6.png)

You have not given containerStyle 
give :- containerStyle={{backgroundColor:"whatever color"}}

**Comment by Hridey27** [comment]
> Is there a way to keep the entire sheet above the keyboard? Currently when the user focuses an input the keyboard will pop up and cover whatever portion of the sheet is below the input that is focused.

Make a Keyboard listener and change height when keyboard shows and reduce height when keyboard hides

Make use of :-
 Keyboard.addListener("keyboardDidShow", () => setkeyboardOpen(true));
  Keyboard.addListener("keyboardDidHide", () => setkeyboardOpen(false));

**Comment by ammarahm-ed** [comment]
@ahmad6242 @Hridey27 Fixed the issue. Also the keyboard issue is resolved on the latest version. It works as expected.

**Comment by ahmad6242** [comment]
Thanks I will test @ammarahm-ed
