### ISSUE TITLE
extra white bar on top and bottom

### ISSUE THREAD

**Issue by Shahanshah87** [ammarahm-ed/react-native-actions-sheet#66]
Extra white bar (background) is coming :-

`<ActionSheet
                        `initialOffsetFromBottom={1}`
                        bounceOnOpen={true}
                        bounciness={8}
                        gestureEnabled={true}
                        ref={actionSheetRef}>
</ActionSheet>
` 
even after `initialOffsetFromBottom={1}` after this.

**Comment by ammarahm-ed** [comment]
@Shahanshah87 Can you send a screenshot or something to explain?
