### ISSUE TITLE
Action sheet is dismissed if clicked on the status bar

### ISSUE THREAD

**Issue by aliceInWahed** [ammarahm-ed/react-native-actions-sheet#69]
Not sure if anyone has this issue. I was testing over the example code. The action sheet is dismissed if I clicked on the status bar. and it is unable to show again, even with the Open ActionSheet button.

https://user-images.githubusercontent.com/79141836/116005476-aebe8400-a639-11eb-886c-c7fbef0aad7c.mov

**Comment by ammarahm-ed** [comment]
I will check.

**Comment by ammarahm-ed** [comment]
Fixed on 0.4.7. now ActionSheet wont close tapping on statusbar
