### ISSUE TITLE
snapToOffset function will trigger _returnToPrevScrollPosition

### ISSUE THREAD

**Issue by aliceInWahed** [ammarahm-ed/react-native-actions-sheet#70]
Hi, I have tried to call snapToOffset function in the CustomHeaderComponent to show like dismissing the action-sheet to the bottom when clicking on the header. 

However, the _onScrollEnd function will get called each time after onScroll function. Again, the action sheet will call _returnToPrevScrollPosition. 

Not sure what do I miss here. Appreciate any helps. Thanks.

https://user-images.githubusercontent.com/79141836/116054421-38a83480-a6ae-11eb-802f-8b881ab4979c.mov

here is the piece of code of my testing
```
        <ActionSheet
          containerStyle={{borderRadius: 32}}
          animated={false}
          initialOffsetFromBottom={0.7}
          ref={actionSheetRef}
          onOpen={onOpen}
          statusBarTranslucent
          onPositionChanged={onHasReachedTop}
          gestureEnabled={true}
          onClose={onClose}
          closable={false}
          bottomOffset={200}
          closeOnPressBack={false}
          CustomHeaderComponent={
              <TouchableOpacity
                onPress={() => {
                  console.log('header is clicked');
                  actionSheetRef.current?.snapToOffset(200);
                }}
              >
                <View style={styles.indicator} />
              </TouchableOpacity>
          }
          defaultOverlayOpacity={0}>
```

the inspiration of the testing is here.

https://user-images.githubusercontent.com/79141836/116055123-fa5f4500-a6ae-11eb-8823-c809e5904ea5.mov

**Comment by ammarahm-ed** [comment]
@aliceInWahed I think I understand the problem. I will fix it.

**Comment by ammarahm-ed** [comment]
@aliceInWahed Hey, I have fixed the problem. Can you test it using the master branch? 

`yarn add https://github.com/ammarahm-ed/react-native-actions-sheet`

**Comment by aliceInWahed** [comment]
HI @ammarahm-ed, thanks for fixes. Yep I have tested. it works well. 🎶

However I realised another issue with the closable and bottomOffset.
as far I set 

` onClose={onClose}
          closable={false}
          bottomOffset={200}`

the action sheet doesn't shift to the bottomOffset value which I set. it is return to the initialOffsetFromBottom value position.

I am not sure if this is a similar issue? 
https://user-images.githubusercontent.com/79141836/116179172-70b08580-a749-11eb-81ac-5f5c16e71b60.mov

Is there possible to dismiss the action sheet to the bottomOffset position, but retain the initialOffsetFromBottom value as the middle scrolling position?

**Comment by ammarahm-ed** [comment]
It is a similar issue. I will investigate it today.

And you are saying that even with closable set to false, the ActionSheet should be dismissable by after going beyond x offset?

**Comment by aliceInWahed** [comment]
Yes yes, that's the idea I have which u have put it in words perfectly. Thank you

**Comment by aliceInWahed** [comment]
Hi @ammarahm-ed, I think the idea is the actionSheet is dismissed to bottomOffset if going beyond x offset, otherwise, go back to initial offset.

**Comment by ammarahm-ed** [comment]
> Hi @ammarahm-ed, sorry for the confusion. 
> 
> I think the idea is the actionSheet is dismissed to bottomOffset if going beyond bottom offset, otherwise, go back to initial offset, with closable set to false 

And what if user pulls down from the bottomOffset? Should the ActionSheet be dismissed even with closable set to false?

**Comment by aliceInWahed** [comment]
nope, to me, I feel the actionSheet should always return to bottomOffset when closable set to false. this is the initial purpose of having closable and bottomOffset, right?

return to bottomOffset if
1. pull down beyond bottomOffset
2. pull down from the bottomOffset/out of the screen

Sorry if I got the wrong idea. :(

**Comment by ammarahm-ed** [comment]
Okay, I will fix the bottomOffset issue.

**Comment by aliceInWahed** [comment]
so if the user scrolls the actionSheet beyond the bottomOffset, the actionSheet will be snap to bottomOffset. When scroll up/down to initialOffset, actionSheet will move up/down and snap to initialOffset. and if scroll to the top, ActionSheet will be in full screen. Otherwise, it will go back to initialOffset value. 

Basically there will be 3 points, top, initial offset, bottom offset. 

Do I get the idea correct?

**Comment by ammarahm-ed** [comment]
@aliceInWahed Yes

**Comment by ammarahm-ed** [comment]
@aliceInWahed i have fixed it on master, can you try again

**Comment by aliceInWahed** [comment]
HI @ammarahm-ed, it's working perfectly. Kudos to u. Thanks a thousand!

**Comment by ammarahm-ed** [comment]
> HI @ammarahm-ed, it's working perfectly. Kudos to u. Thanks a thousand!

Great. I will release the new version then
