### ISSUE TITLE
`onPositionChanged` is required in index.d.ts

### ISSUE THREAD

**Issue by AndreasGS** [ammarahm-ed/react-native-actions-sheet#72]
The documentation says that `onPositionChanged` is not required but it's required in `index.d.ts`.

**Comment by ammarahm-ed** [comment]
I will fix it

**Comment by ammarahm-ed** [comment]
Fixed on master

**Comment by lukebars** [comment]
@ammarahm-ed any news on planned release?

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed any news on planned release? 

Will do today
