### ISSUE TITLE
How to test actions sheet in jest

### ISSUE THREAD

**Issue by blaze-nitd** [ammarahm-ed/react-native-actions-sheet#79]
Hi our team is using Snapshot testing using jest. I am not able to find a suitable way to test this actionsheet.Can you provide a detailed explanation please

**Comment by ammarahm-ed** [comment]
Use the `testID` prop.

**Comment by blaze-nitd** [comment]
How will we invoke the component? I am using forwardRef and passing ref type and actionSheet required props there. Please help

**Comment by johnny-mcfadden-dailypay** [comment]
I'm not sure this is an issue either tbh, this is a jest testing question and not an issue.

**Comment by ammarahm-ed** [comment]
This is also resolved in v0.8.0
