### ISSUE TITLE
Close multiple open action sheets at once

### ISSUE THREAD

**Issue by natemartins** [ammarahm-ed/react-native-actions-sheet#86]
I have multiple action sheets open. An action sheet opens from another action sheet. Image below 

![photo_2021-06-01_07-50-30](https://user-images.githubusercontent.com/49047480/120279571-836d2b80-c2ae-11eb-9dd8-f69f49df5885.jpg)

I want to close all the previously opened action sheets from the last one when an action is performed. It's not currently able to that.

Expected behaviour: Close all open action sheets when action is carried out, for instance, at the click or tap the DONE button

Possible solution: Navigate to another screen in the app but that isn't ideal as I would like the users of the app to remain on the screen they initiated the action sheet from.

Any possible solution to this or a workaround will be highly appreciated

**Comment by ammarahm-ed** [comment]
You can do it only by creating a function that hides all actionsheets using their ref.

**Comment by natemartins** [comment]
Where will this function be placed: in the first or last action sheet? How would you pass the refs to the function seeing as all the action sheets are not opened from one component. Each action sheet is opened from an already open action sheet.

**Comment by ammarahm-ed** [comment]
This is not possible with `SheetManager`.

**Comment by ammarahm-ed** [comment]
@mirzahayat If you want to render multiple Sheets in iOS. You must render the child sheet inside parent.

```js
<ActionSheet>
     <ActionSheet>
        <ActionSheet>
       </ActionSheet>
    </ActionSheet>
</ActionSheet>
```
