### ISSUE TITLE
Drag up operation on actionSheet

### ISSUE THREAD

**Issue by blaze-nitd** [ammarahm-ed/react-native-actions-sheet#89]
Hi, can we have an initial default height and then drag up to increase the height and drag down to decrease just like it happen in other apps? Not able to find how it can be done here. Can you please help.

Also is there any possibility for a maximum height the actionSheet can take in case we don't want it to take up the whole screen height at maximum?

Thanks in advance :)

**Comment by ammarahm-ed** [comment]
Use `containerStyle` to give a max height value

Use `initialOffsetFromBottom` to set offset such as 0.6 means 60% of total.

Use `closable` to prevent action sheet from closing and return to initial value.

**Comment by blaze-nitd** [comment]
0.6 initialOffsetFromBottom worked. But when dragged upward and releasing it it is taking up entire screen height where it should stop at maximumHeight I set. Can you help here :)

**Comment by blaze-nitd** [comment]
Only height worked :D
