### ISSUE TITLE
[Android] Status bar issue

### ISSUE THREAD

**Issue by arakovskis** [ammarahm-ed/react-native-actions-sheet#90]
Hi @ammarahm-ed

Is there any way to make status bar color same as backdrop color when actionsheet is opened?

Device: Pixel 4 emu

![image](https://user-images.githubusercontent.com/43447421/123413365-5b29d180-d5bb-11eb-93b4-c6a9906adcc0.png)

**Comment by ammarahm-ed** [comment]
Maybe import StatusBar from react native and set StatusBar.setTranslucent(true)?
