### ISSUE TITLE
Running on Web: Getting "Uncaught TypeError: Cannot read property 'style' of undefined"

### ISSUE THREAD

**Issue by tomKrueger** [ammarahm-ed/react-native-actions-sheet#91]
When I run on iOS the ActionSheet works fine.  Thank you!

When I run on Web, by simply adding import I get the error

index.js:790 Uncaught TypeError: Cannot read property 'style' of undefined
    at Module.../../../../../../../../../../../Projects/TFS/TomKrueger/VaiaDraftbit/src/VaiaDrafbit/node_modules/react-native-actions-sheet/src/index.js (index.js:790)

This is the part of index.js and looks liike ViewPropTypes is undefined.  Seems to be a common issues with other react native components as well.  Maybe there is a simple solution that you know already.  

ActionSheet.propTypes = {
  testID: PropTypes.string,
  children: PropTypes.node,
  CustomHeaderComponent: PropTypes.node,
  extraScroll: PropTypes.number,
  headerAlwaysVisible: PropTypes.bool,
  **containerStyle: ViewPropTypes.style,**. (Line 790)

Thanks for the help!

**Comment by ammarahm-ed** [comment]
Hey can you test by replacing that with PropTypes.object I think? I am also not sure if we need propTypes? We have typescript definitions

**Comment by ammarahm-ed** [comment]
Fixed
