### ISSUE TITLE
Example App not working on Android (ScrollView inside of ActionSheet)

### ISSUE THREAD

**Issue by saschagehlich** [ammarahm-ed/react-native-actions-sheet#92]
react-native@~0.63.4
react-native-actions-sheet@^0.4.9

ActionSheet opens on button tap, but I can't scroll inside the ScrollView - it only drags around the ActionSheet. Works fine on iOS.

**Comment by projjwalg** [comment]
I am having the same issue. I am using flatlist inside the ActionSheet

**Comment by ammarahm-ed** [comment]
> I am having the same issue. I am using flatlist inside the ActionSheet

Import FlatList from `react-native-gesture-handler` then follow the guide at the end of readme docs.
