### ISSUE TITLE
Opening an action sheet from another action sheet is not working on iOS.

### ISSUE THREAD

**Issue by sahildeliwala** [ammarahm-ed/react-native-actions-sheet#93]
Opening action sheet from already opened action sheet is not working on iOS. It works fine on Android.

When you click option to show another action sheet nothing happens on iOS.

**Comment by ammarahm-ed** [comment]
> Opening action sheet from already opened action sheet is not working on iOS. It works fine on Android.
> 
> When you click option to show another action sheet nothing happens on iOS.

That's a limitation of ios. If you want to open another action sheet. It should exist inside the parent actionsheet to show on ios.

**Comment by Nziranziza** [comment]
> > Opening action sheet from already opened action sheet is not working on iOS. It works fine on Android.
> > When you click option to show another action sheet nothing happens on iOS.
> 
> That's a limitation of ios. If you want to open another action sheet. It should exist inside the parent actionsheet to show on ios.

@ammarahm-ed does this apply to  react native modal?

**Comment by ammarahm-ed** [comment]
Yes.

**Comment by ammarahm-ed** [comment]
> > > Opening action sheet from already opened action sheet is not working on iOS. It works fine on Android.
> > > When you click option to show another action sheet nothing happens on iOS.
> > 
> > That's a limitation of ios. If you want to open another action sheet. It should exist inside the parent actionsheet to show on ios.
> 
> @ammarahm-ed does this apply to  react native modal?

Yes
