### ISSUE TITLE
action sheet flashes on android

### ISSUE THREAD

**Issue by pelaxa** [ammarahm-ed/react-native-actions-sheet#95]
Seems like no matter what properties I set or not set, the action sheet has a sudden flashy bounce in the android simulator.
on rare occasions it is not seen, but more often than not, it is seen.  I tried setting the height of the content inside, and various other properties like animated and bounciness, but nothing seems to make a difference.

```
      <ActionSheet ref={actionSheetRef}>
        <View style={styles.pickerView}>
          <DatePicker
            date={dateTime.toDate()}
            mode={state.type}
            onDateChange={setDate}
            androidVariant={'nativeAndroid'}
          />
        </View>
      </ActionSheet>
```

Am I doing something wrong?

**Comment by ammarahm-ed** [comment]
> Seems like no matter what properties I set or not set, the action sheet has a sudden flashy bounce in the android simulator.
> on rare occasions it is not seen, but more often than not, it is seen.  I tried setting the height of the content inside, and various other properties like animated and bounciness, but nothing seems to make a difference.
> 
> ```
>       <ActionSheet ref={actionSheetRef}>
>         <View style={styles.pickerView}>
>           <DatePicker
>             date={dateTime.toDate()}
>             mode={state.type}
>             onDateChange={setDate}
>             androidVariant={'nativeAndroid'}
>           />
>         </View>
>       </ActionSheet>
> ```
> 
> Am I doing something wrong?

Can you share a small video where the issue can be seen so I have a better idea? 

Also can you try to install the master branch in your project and use it in app. See if that helps?

**Comment by pelaxa** [comment]
Here is a screen recording showing how on show, the action sheet flashes and almost seems to bounce in a jittery motion.
I tried the master branch as well, but this is still happening to me.

https://user-images.githubusercontent.com/4706332/126036502-57b3fb87-81f0-481c-ba75-dc19248a6c50.mov

**Comment by ammarahm-ed** [comment]
> Here is a screen recording showing how on show, the action sheet flashes and almost seems to bounce in a jittery motion.
> I tried the master branch as well, but this is still happening to me.
> 
> https://user-images.githubusercontent.com/4706332/126036502-57b3fb87-81f0-481c-ba75-dc19248a6c50.mov
> 
> 

I have tested the master branch and the example app. I notice no jittering. Maybe it has something to do with the contents inside the Actionsheet you have added. 

If you run the example by cloning master branch, and still see a problem I will try to fix it. But at the moment i can't reproduce this.

**Comment by lewatt23** [comment]
i have the same problem, @pelaxa. Did you resolve it ?

**Comment by ammarahm-ed** [comment]
@lewatt23 Can you post your code here along with the styling you are adding to ActionSheet and internal views?

**Comment by pelaxa** [comment]
> i have the same problem, @pelaxa. Did you resolve it ?

my apologies.  I was under a deadline so i have to move on.  I created a very basic version just to meet my needs, but this by far is one of he best action sheets I saw available.
