### ISSUE TITLE
First action on the ActionSheet isnt working in Android and iOS

### ISSUE THREAD

**Issue by Sriman97** [ammarahm-ed/react-native-actions-sheet#97]
Hi,
I am currently using the ActionSheet to show a few touchable options inside it.
When the ActionSheet is launched, the first action doesn't seem to be working. I tried setting the zIndex as 1, but thats solving the issue only in Android. Is there something I am missing, or is there a better way to do this, could you please help me with it?

To give an idea about the Usage:

There is a parent view which loads another component in which the ActionSheet code is available. something like below:

`<View style={{ flex: 1}}>
.....
<CustomComponent  ref={ref} {...props} />
</View>`

Inside CustomComponent: 
` <> 
  ...
<ActionSheet  ref={ref} containerStyle={{ flex: 1 }} {...} />
</>`

**Comment by ammarahm-ed** [comment]
@Sriman97  Do not use flex.

**Comment by Sriman97** [comment]
@ammarahm-ed Any reason?

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed Any reason? And is there a way I can control the styles by not using a flex? i.e. i need the elements to be coming in a row instead of column, etc.

You can use flex properties but don't use `flex:1` because dimensions are calculated dynamically by ActionSheet. Don't use `flex:1` on container style and in parent View inside ActionSheet.

**Comment by Sriman97** [comment]
I removed all instances of flex: 1, but the issue was still there. Is there something else i can try?

**Comment by ammarahm-ed** [comment]
> I removed all instances of flex: 1, but the issue was still there. Is there something else i can try?

Can you run the example app and see if you face a similar problem? Right now I do not have this issue.

**Comment by Sriman97** [comment]
I was able to start the example app only on Android. Would need help with iOS as it was continuously failing when i run `yarn ios` even after trying couple of fixes.
But if i remove the flex: 1 for the containerView, it was working fine in Android, but still giving issues in iOS.

**Comment by ammarahm-ed** [comment]
@Sriman97 You have to run `pod install` in ios folder then run the app.

**Comment by Sriman97** [comment]
I wasnt able to repro the issue on iOS as well for the example app. Let me check a bit more and get back.

**Comment by Sriman97** [comment]
@ammarahm-ed the fix that you mentioned about removing flex from the parent view. I was testing on iOS with the software keyboard hidden, due to which it was appearing as if the issue was occurring on iOS. Enabled the software keyboard, and the experience is all good. Thanks for your help :)
