### ISSUE TITLE
Doesn't work properly on iOS simulator

### ISSUE THREAD

**Issue by garmoshka-mo** [ammarahm-ed/react-native-actions-sheet#98]
There is random issues when try to use `react-native-actions-sheet` on iOS simulator

In one project I had TouchableOpacity randomly doesn't work (most often onPress doesn't work, though sometimes it works)

For other project only small top piece of actions-sheet shown, and its main part with all content is not visible and unreachable.

On real devices such issues never happen.

**Comment by ammarahm-ed** [comment]
> There is random issues when try to use `react-native-actions-sheet` on iOS simulator
> 
> In one project I had TouchableOpacity randomly doesn't work (most often onPress doesn't work, though sometimes it works)
> 
> For other project only small top piece of actions-sheet shown, and its main part with all content is not visible and unreachable.
> 
> On real devices such issues never happen.

The example app works normally on iOS simulator and devices both. Match your styling etc with the example or post your code where you had such issues
