### ISSUE TITLE
How can i use snapToOffset(offset:number) directly if the actionsheet is closed

### ISSUE THREAD

**Issue by ahmad6242** [ammarahm-ed/react-native-actions-sheet#99]
snapToOffset(offset:number)

What i want is to open the action sheet to a specific offset, without opening it first to full height and then calling this function.

For now i am doing it like this. But this is not performing very well sometimes it works sometimes it don't 
` initialOpenMenu = () => {

        console.log('here1');
        this.refMenuActions.current?.setModalVisible(true);

        setTimeout(() => {
            console.log('here2');

            this.refMenuActions.current?.snapToOffset(85);

        }, 300);

    }
`

Can you please help here.

**Comment by ammarahm-ed** [comment]
use `initialOffsetFromBottom` prop.

**Comment by ahmad6242** [comment]
initialOffsetFromBottom this does not work . When i use this it do something like this 

BEFORE

![Screenshot_1628058823](https://user-images.githubusercontent.com/12858657/128133252-0c02a22f-3b6e-4b20-942b-beab762f2c30.png)


AFTER initialOffsetFromBottom={85}

![Screenshot_1628058851](https://user-images.githubusercontent.com/12858657/128133268-6ce6818f-1b91-4a0b-a1c0-9d3fd830f13a.png)


And it always open full !!!!

**Comment by ammarahm-ed** [comment]
> initialOffsetFromBottom this does not work . When i use this it do something like this 
> 
> BEFORE
> 
> ![Screenshot_1628058823](https://user-images.githubusercontent.com/12858657/128133252-0c02a22f-3b6e-4b20-942b-beab762f2c30.png)
> 
> 
> AFTER initialOffsetFromBottom={85}
> 
> ![Screenshot_1628058851](https://user-images.githubusercontent.com/12858657/128133268-6ce6818f-1b91-4a0b-a1c0-9d3fd830f13a.png)
> 
> 
> And it always open full !!!!
> @ammarahm-ed 

The value should be between 0 and 1.

**Comment by ahmad6242** [comment]
So for different Screen sizes it will open in different heights. It should be specific. 
But anyway thanks for the clarification.
